// Code generated by protoc-gen-go.
// source: l2.proto
// DO NOT EDIT!

/*
Package l2 is a generated protocol buffer package.

It is generated from these files:
	l2.proto

It has these top-level messages:
	Address
	CacheAddress
	AddAddressRequest
	AddAddressResponse
	DeleteAddressRequest
	DeleteAddressResponse
	DeleteAddressByPortRequest
	DeleteAddressByPortResponse
	DeleteAddressByMACRequest
	DeleteAddressByMACResponse
	DeleteAddressByVLANRequest
	DeleteAddressByVLANResponse
	DeleteAddressByTrunkRequest
	DeleteAddressByTrunkResponse
	DeleteAddressByMACPortRequest
	DeleteAddressByMACPortResponse
	DeleteAddressByVLANPortRequest
	DeleteAddressByVLANPortResponse
	DeleteAddressByVLANTrunkRequest
	DeleteAddressByVLANTrunkResponse
	GetAddressRequest
	GetAddressResponse
	MonitorRequest
	MonitorResponse
	SetAgeTimerRequest
	SetAgeTimerResponse
	GetAgeTimerRequest
	GetAgeTimerResponse
	ListRequest
	ListResponse
	Station
	StationAddRequest
	StationAddResponse
	StationDeleteRequest
	StationDeleteResponse
	StationGetRequest
	StationGetResponse
*/
package l2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type L2Flag int32

const (
	L2Flag_FLAG_UNKNOWN     L2Flag = 0
	L2Flag_FLAG_DISCARD_SRC L2Flag = 2
	L2Flag_FLAG_DISCARD_DST L2Flag = 4
	L2Flag_FLAG_L3LOOKUP    L2Flag = 16
	L2Flag_FLAG_STATIC      L2Flag = 32
	L2Flag_FLAG_MOVE_PORT   L2Flag = 1048576
)

var L2Flag_name = map[int32]string{
	0:       "FLAG_UNKNOWN",
	2:       "FLAG_DISCARD_SRC",
	4:       "FLAG_DISCARD_DST",
	16:      "FLAG_L3LOOKUP",
	32:      "FLAG_STATIC",
	1048576: "FLAG_MOVE_PORT",
}
var L2Flag_value = map[string]int32{
	"FLAG_UNKNOWN":     0,
	"FLAG_DISCARD_SRC": 2,
	"FLAG_DISCARD_DST": 4,
	"FLAG_L3LOOKUP":    16,
	"FLAG_STATIC":      32,
	"FLAG_MOVE_PORT":   1048576,
}

func (x L2Flag) String() string {
	return proto.EnumName(L2Flag_name, int32(x))
}
func (L2Flag) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type L2Operation int32

const (
	L2Operation_DELETE      L2Operation = 0
	L2Operation_ADD         L2Operation = 1
	L2Operation_REPORT      L2Operation = 2
	L2Operation_LEARN_EVENT L2Operation = 3
	L2Operation_AGE_EVENT   L2Operation = 4
	L2Operation_MOVE_EVENT  L2Operation = 5
)

var L2Operation_name = map[int32]string{
	0: "DELETE",
	1: "ADD",
	2: "REPORT",
	3: "LEARN_EVENT",
	4: "AGE_EVENT",
	5: "MOVE_EVENT",
}
var L2Operation_value = map[string]int32{
	"DELETE":      0,
	"ADD":         1,
	"REPORT":      2,
	"LEARN_EVENT": 3,
	"AGE_EVENT":   4,
	"MOVE_EVENT":  5,
}

func (x L2Operation) String() string {
	return proto.EnumName(L2Operation_name, int32(x))
}
func (L2Operation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type L2CacheFlag int32

const (
	L2CacheFlag_CPU     L2CacheFlag = 0
	L2CacheFlag_DISCARD L2CacheFlag = 1
	L2CacheFlag_BPDU    L2CacheFlag = 16
)

var L2CacheFlag_name = map[int32]string{
	0:  "CPU",
	1:  "DISCARD",
	16: "BPDU",
}
var L2CacheFlag_value = map[string]int32{
	"CPU":     0,
	"DISCARD": 1,
	"BPDU":    16,
}

func (x L2CacheFlag) String() string {
	return proto.EnumName(L2CacheFlag_name, int32(x))
}
func (L2CacheFlag) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type L2DeleteFlag int32

const (
	L2DeleteFlag_DELETE_UNKNOWN      L2DeleteFlag = 0
	L2DeleteFlag_DELETE_STATIC       L2DeleteFlag = 1
	L2DeleteFlag_DELETE_PENDING      L2DeleteFlag = 2
	L2DeleteFlag_DELETE_NO_CALLBACKS L2DeleteFlag = 3
)

var L2DeleteFlag_name = map[int32]string{
	0: "DELETE_UNKNOWN",
	1: "DELETE_STATIC",
	2: "DELETE_PENDING",
	3: "DELETE_NO_CALLBACKS",
}
var L2DeleteFlag_value = map[string]int32{
	"DELETE_UNKNOWN":      0,
	"DELETE_STATIC":       1,
	"DELETE_PENDING":      2,
	"DELETE_NO_CALLBACKS": 3,
}

func (x L2DeleteFlag) String() string {
	return proto.EnumName(L2DeleteFlag_name, int32(x))
}
func (L2DeleteFlag) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type L2StationFlag int32

const (
	L2StationFlag_STATION_UNKNOWN  L2StationFlag = 0
	L2StationFlag_STATION_WITH_ID  L2StationFlag = 1
	L2StationFlag_STATION_IPV4     L2StationFlag = 2
	L2StationFlag_STATION_IPV6     L2StationFlag = 4
	L2StationFlag_STATION_ARP_RARP L2StationFlag = 8
)

var L2StationFlag_name = map[int32]string{
	0: "STATION_UNKNOWN",
	1: "STATION_WITH_ID",
	2: "STATION_IPV4",
	4: "STATION_IPV6",
	8: "STATION_ARP_RARP",
}
var L2StationFlag_value = map[string]int32{
	"STATION_UNKNOWN":  0,
	"STATION_WITH_ID":  1,
	"STATION_IPV4":     2,
	"STATION_IPV6":     4,
	"STATION_ARP_RARP": 8,
}

func (x L2StationFlag) String() string {
	return proto.EnumName(L2StationFlag_name, int32(x))
}
func (L2StationFlag) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Address struct {
	Flags L2Flag `protobuf:"varint,1,opt,name=flags,enum=l2.L2Flag" json:"flags,omitempty"`
	//    uint32 reserved1 = 2;
	Mac     []byte `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	Vid     uint32 `protobuf:"varint,4,opt,name=vid" json:"vid,omitempty"`
	Port    int64  `protobuf:"varint,5,opt,name=port" json:"port,omitempty"`
	ModId   int64  `protobuf:"varint,6,opt,name=mod_id,json=modId" json:"mod_id,omitempty"`
	TrunkId int64  `protobuf:"varint,7,opt,name=trunk_id,json=trunkId" json:"trunk_id,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CacheAddress struct {
	Flags         uint32   `protobuf:"varint,1,opt,name=flags" json:"flags,omitempty"`
	StationFlags  uint32   `protobuf:"varint,2,opt,name=station_flags,json=stationFlags" json:"station_flags,omitempty"`
	Mac           []byte   `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	MacMask       []byte   `protobuf:"bytes,4,opt,name=mac_mask,json=macMask,proto3" json:"mac_mask,omitempty"`
	Vid           uint32   `protobuf:"varint,5,opt,name=vid" json:"vid,omitempty"`
	VidMask       uint32   `protobuf:"varint,6,opt,name=vid_mask,json=vidMask" json:"vid_mask,omitempty"`
	SrcPort       int64    `protobuf:"varint,7,opt,name=src_port,json=srcPort" json:"src_port,omitempty"`
	SrcPortMask   int64    `protobuf:"varint,8,opt,name=src_port_mask,json=srcPortMask" json:"src_port_mask,omitempty"`
	DstModId      int64    `protobuf:"varint,9,opt,name=dst_mod_id,json=dstModId" json:"dst_mod_id,omitempty"`
	DstPort       int64    `protobuf:"varint,10,opt,name=dst_port,json=dstPort" json:"dst_port,omitempty"`
	DstTrunk      int64    `protobuf:"varint,11,opt,name=dst_trunk,json=dstTrunk" json:"dst_trunk,omitempty"`
	Prio          int64    `protobuf:"varint,12,opt,name=prio" json:"prio,omitempty"`
	DstPorts      []uint32 `protobuf:"varint,13,rep,name=dst_ports,json=dstPorts" json:"dst_ports,omitempty"`
	LookupClass   int64    `protobuf:"varint,14,opt,name=lookup_class,json=lookupClass" json:"lookup_class,omitempty"`
	Subtype       uint32   `protobuf:"varint,15,opt,name=subtype" json:"subtype,omitempty"`
	EncapId       int64    `protobuf:"varint,16,opt,name=encap_id,json=encapId" json:"encap_id,omitempty"`
	Group         int64    `protobuf:"varint,17,opt,name=group" json:"group,omitempty"`
	Ethertype     uint32   `protobuf:"varint,18,opt,name=ethertype" json:"ethertype,omitempty"`
	EthertypeMask uint32   `protobuf:"varint,19,opt,name=ethertype_mask,json=ethertypeMask" json:"ethertype_mask,omitempty"`
}

func (m *CacheAddress) Reset()                    { *m = CacheAddress{} }
func (m *CacheAddress) String() string            { return proto.CompactTextString(m) }
func (*CacheAddress) ProtoMessage()               {}
func (*CacheAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AddAddressRequest struct {
	Unit    int64    `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Address *Address `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *AddAddressRequest) Reset()                    { *m = AddAddressRequest{} }
func (m *AddAddressRequest) String() string            { return proto.CompactTextString(m) }
func (*AddAddressRequest) ProtoMessage()               {}
func (*AddAddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddAddressRequest) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type AddAddressResponse struct {
}

func (m *AddAddressResponse) Reset()                    { *m = AddAddressResponse{} }
func (m *AddAddressResponse) String() string            { return proto.CompactTextString(m) }
func (*AddAddressResponse) ProtoMessage()               {}
func (*AddAddressResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteAddressRequest struct {
	Unit int64  `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Mac  []byte `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Vid  uint32 `protobuf:"varint,3,opt,name=vid" json:"vid,omitempty"`
}

func (m *DeleteAddressRequest) Reset()                    { *m = DeleteAddressRequest{} }
func (m *DeleteAddressRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressRequest) ProtoMessage()               {}
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeleteAddressResponse struct {
}

func (m *DeleteAddressResponse) Reset()                    { *m = DeleteAddressResponse{} }
func (m *DeleteAddressResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressResponse) ProtoMessage()               {}
func (*DeleteAddressResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DeleteAddressByPortRequest struct {
	Unit  int64        `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Mod   int64        `protobuf:"varint,2,opt,name=mod" json:"mod,omitempty"`
	Port  int64        `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Flags L2DeleteFlag `protobuf:"varint,4,opt,name=flags,enum=l2.L2DeleteFlag" json:"flags,omitempty"`
}

func (m *DeleteAddressByPortRequest) Reset()                    { *m = DeleteAddressByPortRequest{} }
func (m *DeleteAddressByPortRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressByPortRequest) ProtoMessage()               {}
func (*DeleteAddressByPortRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DeleteAddressByPortResponse struct {
}

func (m *DeleteAddressByPortResponse) Reset()                    { *m = DeleteAddressByPortResponse{} }
func (m *DeleteAddressByPortResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressByPortResponse) ProtoMessage()               {}
func (*DeleteAddressByPortResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type DeleteAddressByMACRequest struct {
	Unit  int64        `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Mac   []byte       `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Flags L2DeleteFlag `protobuf:"varint,3,opt,name=flags,enum=l2.L2DeleteFlag" json:"flags,omitempty"`
}

func (m *DeleteAddressByMACRequest) Reset()                    { *m = DeleteAddressByMACRequest{} }
func (m *DeleteAddressByMACRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressByMACRequest) ProtoMessage()               {}
func (*DeleteAddressByMACRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type DeleteAddressByMACResponse struct {
}

func (m *DeleteAddressByMACResponse) Reset()                    { *m = DeleteAddressByMACResponse{} }
func (m *DeleteAddressByMACResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressByMACResponse) ProtoMessage()               {}
func (*DeleteAddressByMACResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type DeleteAddressByVLANRequest struct {
	Unit  int64        `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Vid   uint32       `protobuf:"varint,2,opt,name=vid" json:"vid,omitempty"`
	Flags L2DeleteFlag `protobuf:"varint,3,opt,name=flags,enum=l2.L2DeleteFlag" json:"flags,omitempty"`
}

func (m *DeleteAddressByVLANRequest) Reset()                    { *m = DeleteAddressByVLANRequest{} }
func (m *DeleteAddressByVLANRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressByVLANRequest) ProtoMessage()               {}
func (*DeleteAddressByVLANRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type DeleteAddressByVLANResponse struct {
}

func (m *DeleteAddressByVLANResponse) Reset()                    { *m = DeleteAddressByVLANResponse{} }
func (m *DeleteAddressByVLANResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressByVLANResponse) ProtoMessage()               {}
func (*DeleteAddressByVLANResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type DeleteAddressByTrunkRequest struct {
	Unit  int64        `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Tid   int64        `protobuf:"varint,2,opt,name=tid" json:"tid,omitempty"`
	Flags L2DeleteFlag `protobuf:"varint,3,opt,name=flags,enum=l2.L2DeleteFlag" json:"flags,omitempty"`
}

func (m *DeleteAddressByTrunkRequest) Reset()                    { *m = DeleteAddressByTrunkRequest{} }
func (m *DeleteAddressByTrunkRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressByTrunkRequest) ProtoMessage()               {}
func (*DeleteAddressByTrunkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type DeleteAddressByTrunkResponse struct {
}

func (m *DeleteAddressByTrunkResponse) Reset()                    { *m = DeleteAddressByTrunkResponse{} }
func (m *DeleteAddressByTrunkResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressByTrunkResponse) ProtoMessage()               {}
func (*DeleteAddressByTrunkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type DeleteAddressByMACPortRequest struct {
	Unit  int64        `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Mac   []byte       `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Mod   int64        `protobuf:"varint,3,opt,name=mod" json:"mod,omitempty"`
	Port  int64        `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	Flags L2DeleteFlag `protobuf:"varint,5,opt,name=flags,enum=l2.L2DeleteFlag" json:"flags,omitempty"`
}

func (m *DeleteAddressByMACPortRequest) Reset()                    { *m = DeleteAddressByMACPortRequest{} }
func (m *DeleteAddressByMACPortRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressByMACPortRequest) ProtoMessage()               {}
func (*DeleteAddressByMACPortRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type DeleteAddressByMACPortResponse struct {
}

func (m *DeleteAddressByMACPortResponse) Reset()                    { *m = DeleteAddressByMACPortResponse{} }
func (m *DeleteAddressByMACPortResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressByMACPortResponse) ProtoMessage()               {}
func (*DeleteAddressByMACPortResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type DeleteAddressByVLANPortRequest struct {
	Unit  int64        `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Vid   uint32       `protobuf:"varint,2,opt,name=vid" json:"vid,omitempty"`
	Mod   int64        `protobuf:"varint,3,opt,name=mod" json:"mod,omitempty"`
	Port  int64        `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	Flags L2DeleteFlag `protobuf:"varint,5,opt,name=flags,enum=l2.L2DeleteFlag" json:"flags,omitempty"`
}

func (m *DeleteAddressByVLANPortRequest) Reset()                    { *m = DeleteAddressByVLANPortRequest{} }
func (m *DeleteAddressByVLANPortRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressByVLANPortRequest) ProtoMessage()               {}
func (*DeleteAddressByVLANPortRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type DeleteAddressByVLANPortResponse struct {
}

func (m *DeleteAddressByVLANPortResponse) Reset()         { *m = DeleteAddressByVLANPortResponse{} }
func (m *DeleteAddressByVLANPortResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAddressByVLANPortResponse) ProtoMessage()    {}
func (*DeleteAddressByVLANPortResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{17}
}

type DeleteAddressByVLANTrunkRequest struct {
	Unit  int64        `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Vid   uint32       `protobuf:"varint,2,opt,name=vid" json:"vid,omitempty"`
	Tid   int64        `protobuf:"varint,3,opt,name=tid" json:"tid,omitempty"`
	Flags L2DeleteFlag `protobuf:"varint,4,opt,name=flags,enum=l2.L2DeleteFlag" json:"flags,omitempty"`
}

func (m *DeleteAddressByVLANTrunkRequest) Reset()         { *m = DeleteAddressByVLANTrunkRequest{} }
func (m *DeleteAddressByVLANTrunkRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAddressByVLANTrunkRequest) ProtoMessage()    {}
func (*DeleteAddressByVLANTrunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{18}
}

type DeleteAddressByVLANTrunkResponse struct {
}

func (m *DeleteAddressByVLANTrunkResponse) Reset()         { *m = DeleteAddressByVLANTrunkResponse{} }
func (m *DeleteAddressByVLANTrunkResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAddressByVLANTrunkResponse) ProtoMessage()    {}
func (*DeleteAddressByVLANTrunkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{19}
}

type GetAddressRequest struct {
	Unit int64  `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Mac  []byte `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Vid  uint32 `protobuf:"varint,3,opt,name=vid" json:"vid,omitempty"`
}

func (m *GetAddressRequest) Reset()                    { *m = GetAddressRequest{} }
func (m *GetAddressRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAddressRequest) ProtoMessage()               {}
func (*GetAddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type GetAddressResponse struct {
	Address *Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *GetAddressResponse) Reset()                    { *m = GetAddressResponse{} }
func (m *GetAddressResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAddressResponse) ProtoMessage()               {}
func (*GetAddressResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *GetAddressResponse) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type MonitorRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
}

func (m *MonitorRequest) Reset()                    { *m = MonitorRequest{} }
func (m *MonitorRequest) String() string            { return proto.CompactTextString(m) }
func (*MonitorRequest) ProtoMessage()               {}
func (*MonitorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type MonitorResponse struct {
	Unit      int64       `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Address   *Address    `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Operation L2Operation `protobuf:"varint,3,opt,name=operation,enum=l2.L2Operation" json:"operation,omitempty"`
}

func (m *MonitorResponse) Reset()                    { *m = MonitorResponse{} }
func (m *MonitorResponse) String() string            { return proto.CompactTextString(m) }
func (*MonitorResponse) ProtoMessage()               {}
func (*MonitorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *MonitorResponse) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type SetAgeTimerRequest struct {
	Unit       int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	AgeSeconds int64 `protobuf:"varint,2,opt,name=age_seconds,json=ageSeconds" json:"age_seconds,omitempty"`
}

func (m *SetAgeTimerRequest) Reset()                    { *m = SetAgeTimerRequest{} }
func (m *SetAgeTimerRequest) String() string            { return proto.CompactTextString(m) }
func (*SetAgeTimerRequest) ProtoMessage()               {}
func (*SetAgeTimerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type SetAgeTimerResponse struct {
}

func (m *SetAgeTimerResponse) Reset()                    { *m = SetAgeTimerResponse{} }
func (m *SetAgeTimerResponse) String() string            { return proto.CompactTextString(m) }
func (*SetAgeTimerResponse) ProtoMessage()               {}
func (*SetAgeTimerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type GetAgeTimerRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
}

func (m *GetAgeTimerRequest) Reset()                    { *m = GetAgeTimerRequest{} }
func (m *GetAgeTimerRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAgeTimerRequest) ProtoMessage()               {}
func (*GetAgeTimerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

type GetAgeTimerResponse struct {
	AgeSeconds int64 `protobuf:"varint,1,opt,name=age_seconds,json=ageSeconds" json:"age_seconds,omitempty"`
}

func (m *GetAgeTimerResponse) Reset()                    { *m = GetAgeTimerResponse{} }
func (m *GetAgeTimerResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAgeTimerResponse) ProtoMessage()               {}
func (*GetAgeTimerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type ListRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type ListResponse struct {
	List []*Address `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *ListResponse) GetList() []*Address {
	if m != nil {
		return m.List
	}
	return nil
}

type Station struct {
	Flags      L2StationFlag `protobuf:"varint,1,opt,name=flags,enum=l2.L2StationFlag" json:"flags,omitempty"`
	DstMac     []byte        `protobuf:"bytes,2,opt,name=dst_mac,json=dstMac,proto3" json:"dst_mac,omitempty"`
	DstMacMask []byte        `protobuf:"bytes,3,opt,name=dst_mac_mask,json=dstMacMask,proto3" json:"dst_mac_mask,omitempty"`
	Vid        uint32        `protobuf:"varint,4,opt,name=vid" json:"vid,omitempty"`
	VidMask    uint32        `protobuf:"varint,5,opt,name=vid_mask,json=vidMask" json:"vid_mask,omitempty"`
}

func (m *Station) Reset()                    { *m = Station{} }
func (m *Station) String() string            { return proto.CompactTextString(m) }
func (*Station) ProtoMessage()               {}
func (*Station) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

type StationAddRequest struct {
	Unit      int64    `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	StationId int64    `protobuf:"varint,2,opt,name=station_id,json=stationId" json:"station_id,omitempty"`
	Station   *Station `protobuf:"bytes,3,opt,name=station" json:"station,omitempty"`
}

func (m *StationAddRequest) Reset()                    { *m = StationAddRequest{} }
func (m *StationAddRequest) String() string            { return proto.CompactTextString(m) }
func (*StationAddRequest) ProtoMessage()               {}
func (*StationAddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *StationAddRequest) GetStation() *Station {
	if m != nil {
		return m.Station
	}
	return nil
}

type StationAddResponse struct {
	StationId int64 `protobuf:"varint,1,opt,name=station_id,json=stationId" json:"station_id,omitempty"`
}

func (m *StationAddResponse) Reset()                    { *m = StationAddResponse{} }
func (m *StationAddResponse) String() string            { return proto.CompactTextString(m) }
func (*StationAddResponse) ProtoMessage()               {}
func (*StationAddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

type StationDeleteRequest struct {
	Unit      int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	StationId int64 `protobuf:"varint,2,opt,name=station_id,json=stationId" json:"station_id,omitempty"`
}

func (m *StationDeleteRequest) Reset()                    { *m = StationDeleteRequest{} }
func (m *StationDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*StationDeleteRequest) ProtoMessage()               {}
func (*StationDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

type StationDeleteResponse struct {
}

func (m *StationDeleteResponse) Reset()                    { *m = StationDeleteResponse{} }
func (m *StationDeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*StationDeleteResponse) ProtoMessage()               {}
func (*StationDeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

type StationGetRequest struct {
	Unit      int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	StationId int64 `protobuf:"varint,2,opt,name=station_id,json=stationId" json:"station_id,omitempty"`
}

func (m *StationGetRequest) Reset()                    { *m = StationGetRequest{} }
func (m *StationGetRequest) String() string            { return proto.CompactTextString(m) }
func (*StationGetRequest) ProtoMessage()               {}
func (*StationGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

type StationGetResponse struct {
	Station *Station `protobuf:"bytes,1,opt,name=station" json:"station,omitempty"`
}

func (m *StationGetResponse) Reset()                    { *m = StationGetResponse{} }
func (m *StationGetResponse) String() string            { return proto.CompactTextString(m) }
func (*StationGetResponse) ProtoMessage()               {}
func (*StationGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *StationGetResponse) GetStation() *Station {
	if m != nil {
		return m.Station
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "l2.Address")
	proto.RegisterType((*CacheAddress)(nil), "l2.CacheAddress")
	proto.RegisterType((*AddAddressRequest)(nil), "l2.AddAddressRequest")
	proto.RegisterType((*AddAddressResponse)(nil), "l2.AddAddressResponse")
	proto.RegisterType((*DeleteAddressRequest)(nil), "l2.DeleteAddressRequest")
	proto.RegisterType((*DeleteAddressResponse)(nil), "l2.DeleteAddressResponse")
	proto.RegisterType((*DeleteAddressByPortRequest)(nil), "l2.DeleteAddressByPortRequest")
	proto.RegisterType((*DeleteAddressByPortResponse)(nil), "l2.DeleteAddressByPortResponse")
	proto.RegisterType((*DeleteAddressByMACRequest)(nil), "l2.DeleteAddressByMACRequest")
	proto.RegisterType((*DeleteAddressByMACResponse)(nil), "l2.DeleteAddressByMACResponse")
	proto.RegisterType((*DeleteAddressByVLANRequest)(nil), "l2.DeleteAddressByVLANRequest")
	proto.RegisterType((*DeleteAddressByVLANResponse)(nil), "l2.DeleteAddressByVLANResponse")
	proto.RegisterType((*DeleteAddressByTrunkRequest)(nil), "l2.DeleteAddressByTrunkRequest")
	proto.RegisterType((*DeleteAddressByTrunkResponse)(nil), "l2.DeleteAddressByTrunkResponse")
	proto.RegisterType((*DeleteAddressByMACPortRequest)(nil), "l2.DeleteAddressByMACPortRequest")
	proto.RegisterType((*DeleteAddressByMACPortResponse)(nil), "l2.DeleteAddressByMACPortResponse")
	proto.RegisterType((*DeleteAddressByVLANPortRequest)(nil), "l2.DeleteAddressByVLANPortRequest")
	proto.RegisterType((*DeleteAddressByVLANPortResponse)(nil), "l2.DeleteAddressByVLANPortResponse")
	proto.RegisterType((*DeleteAddressByVLANTrunkRequest)(nil), "l2.DeleteAddressByVLANTrunkRequest")
	proto.RegisterType((*DeleteAddressByVLANTrunkResponse)(nil), "l2.DeleteAddressByVLANTrunkResponse")
	proto.RegisterType((*GetAddressRequest)(nil), "l2.GetAddressRequest")
	proto.RegisterType((*GetAddressResponse)(nil), "l2.GetAddressResponse")
	proto.RegisterType((*MonitorRequest)(nil), "l2.MonitorRequest")
	proto.RegisterType((*MonitorResponse)(nil), "l2.MonitorResponse")
	proto.RegisterType((*SetAgeTimerRequest)(nil), "l2.SetAgeTimerRequest")
	proto.RegisterType((*SetAgeTimerResponse)(nil), "l2.SetAgeTimerResponse")
	proto.RegisterType((*GetAgeTimerRequest)(nil), "l2.GetAgeTimerRequest")
	proto.RegisterType((*GetAgeTimerResponse)(nil), "l2.GetAgeTimerResponse")
	proto.RegisterType((*ListRequest)(nil), "l2.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "l2.ListResponse")
	proto.RegisterType((*Station)(nil), "l2.Station")
	proto.RegisterType((*StationAddRequest)(nil), "l2.StationAddRequest")
	proto.RegisterType((*StationAddResponse)(nil), "l2.StationAddResponse")
	proto.RegisterType((*StationDeleteRequest)(nil), "l2.StationDeleteRequest")
	proto.RegisterType((*StationDeleteResponse)(nil), "l2.StationDeleteResponse")
	proto.RegisterType((*StationGetRequest)(nil), "l2.StationGetRequest")
	proto.RegisterType((*StationGetResponse)(nil), "l2.StationGetResponse")
	proto.RegisterEnum("l2.L2Flag", L2Flag_name, L2Flag_value)
	proto.RegisterEnum("l2.L2Operation", L2Operation_name, L2Operation_value)
	proto.RegisterEnum("l2.L2CacheFlag", L2CacheFlag_name, L2CacheFlag_value)
	proto.RegisterEnum("l2.L2DeleteFlag", L2DeleteFlag_name, L2DeleteFlag_value)
	proto.RegisterEnum("l2.L2StationFlag", L2StationFlag_name, L2StationFlag_value)
}

func init() { proto.RegisterFile("l2.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x57, 0x5b, 0x6f, 0xdb, 0x56,
	0x0c, 0x9e, 0x2c, 0x5f, 0xe9, 0x4b, 0xe4, 0x93, 0x14, 0x75, 0xd7, 0xa4, 0x75, 0xb4, 0x5b, 0x11,
	0xa0, 0x1d, 0x90, 0x0c, 0x7d, 0xe9, 0xcb, 0x14, 0xdb, 0xc9, 0x8c, 0x38, 0xb2, 0x21, 0x3b, 0xe9,
	0xdb, 0x04, 0xc7, 0xd6, 0x52, 0x2f, 0x8e, 0xe5, 0x59, 0xf2, 0x80, 0x62, 0xc0, 0x90, 0xfd, 0x86,
	0x6d, 0x2f, 0xc3, 0x7e, 0xec, 0x78, 0x78, 0x8e, 0x64, 0xd9, 0x4a, 0x9c, 0xb4, 0xeb, 0x4b, 0x2c,
	0x7e, 0xe4, 0x21, 0x3f, 0xf2, 0x90, 0x0a, 0x05, 0xd9, 0xf1, 0xfe, 0xab, 0xe9, 0xcc, 0xf5, 0x5d,
	0x96, 0x18, 0xef, 0xeb, 0x7f, 0x2b, 0x90, 0x31, 0x86, 0xc3, 0x99, 0xe3, 0x79, 0xac, 0x0a, 0xa9,
	0x9f, 0xc6, 0xfd, 0x4b, 0xaf, 0xa2, 0x54, 0x95, 0x17, 0xa5, 0x7d, 0x78, 0x85, 0x96, 0xad, 0xfd,
	0x23, 0x84, 0x2c, 0xa1, 0x60, 0x1a, 0xa8, 0xd7, 0xfd, 0x41, 0x45, 0x45, 0x7d, 0xc1, 0xe2, 0x8f,
	0x1c, 0xf9, 0x75, 0x34, 0xac, 0x24, 0x11, 0x29, 0x5a, 0xfc, 0x91, 0x31, 0x48, 0x4e, 0xdd, 0x99,
	0x5f, 0x49, 0x21, 0xa4, 0x5a, 0xf4, 0xcc, 0x1e, 0x41, 0xfa, 0xda, 0x1d, 0xda, 0x68, 0x98, 0x26,
	0x34, 0x85, 0x52, 0x73, 0xc8, 0x9e, 0x40, 0xd6, 0x9f, 0xcd, 0x27, 0x57, 0x5c, 0x91, 0x21, 0x45,
	0x86, 0xe4, 0xe6, 0x50, 0xff, 0x37, 0x09, 0x85, 0x5a, 0x7f, 0xf0, 0xce, 0x09, 0xc8, 0x6d, 0x45,
	0xc9, 0x15, 0x03, 0x42, 0x5f, 0x40, 0xd1, 0xf3, 0xfb, 0xfe, 0xc8, 0x9d, 0xd8, 0x42, 0x9b, 0x20,
	0x6d, 0x41, 0x82, 0x47, 0x77, 0xb0, 0xc6, 0xc0, 0xf8, 0x63, 0x5f, 0xf7, 0xbd, 0x2b, 0xa2, 0x5e,
	0xb0, 0x32, 0x28, 0x9f, 0xa2, 0x18, 0x24, 0x94, 0x5a, 0x24, 0x84, 0xc6, 0xf8, 0x23, 0x8c, 0xd3,
	0x04, 0x67, 0x50, 0x26, 0x63, 0x54, 0x79, 0xb3, 0x81, 0x4d, 0xf9, 0xca, 0x04, 0x50, 0xee, 0xf0,
	0x94, 0x75, 0x64, 0x26, 0x55, 0xe2, 0x68, 0x96, 0xf4, 0x79, 0xa9, 0xa7, 0xe3, 0xdb, 0x00, 0x43,
	0x0f, 0xd5, 0xa2, 0x34, 0x39, 0x32, 0xc8, 0x22, 0x72, 0x1a, 0x54, 0x87, 0x6b, 0xc9, 0x39, 0x08,
	0xe7, 0x28, 0x93, 0xf3, 0xa7, 0x90, 0xe3, 0x2a, 0x2a, 0x56, 0x25, 0x1f, 0x9e, 0xeb, 0x71, 0x99,
	0x2e, 0x60, 0x36, 0x72, 0x2b, 0x05, 0x79, 0x01, 0xf8, 0x1c, 0x1c, 0xe0, 0xbe, 0xbc, 0x4a, 0xb1,
	0xaa, 0x62, 0x12, 0x59, 0xe9, 0xcc, 0x63, 0xbb, 0x50, 0x18, 0xbb, 0xee, 0xd5, 0x7c, 0x6a, 0x0f,
	0xc6, 0x7d, 0xcf, 0xab, 0x94, 0x04, 0x53, 0x81, 0xd5, 0x38, 0xc4, 0x2a, 0x90, 0xf1, 0xe6, 0x17,
	0xfe, 0xfb, 0xa9, 0x53, 0xd9, 0x10, 0x25, 0x90, 0x22, 0x67, 0xe9, 0x4c, 0x06, 0xfd, 0x29, 0xcf,
	0x40, 0x13, 0x2c, 0x49, 0xc6, 0x04, 0xf0, 0xca, 0x2e, 0x67, 0xee, 0x7c, 0x5a, 0x29, 0x8b, 0x4b,
	0x27, 0x01, 0x93, 0xce, 0x39, 0xfe, 0x3b, 0x67, 0x46, 0xce, 0x18, 0x39, 0x5b, 0x00, 0xec, 0x2b,
	0x28, 0x85, 0x82, 0xa8, 0xdb, 0x26, 0x99, 0x14, 0x43, 0x94, 0x57, 0x4e, 0x37, 0xa1, 0x8c, 0x8d,
	0x21, 0x7b, 0xc3, 0x72, 0x7e, 0x99, 0x3b, 0x9e, 0xcf, 0x13, 0x9f, 0x4f, 0x46, 0x3e, 0x75, 0x08,
	0x26, 0xce, 0x9f, 0xd1, 0x5f, 0xa6, 0x2f, 0xac, 0xa8, 0x35, 0xf2, 0xfb, 0x79, 0xde, 0xd5, 0xc1,
	0xc1, 0x40, 0xa7, 0x6f, 0x01, 0x8b, 0xfa, 0xf3, 0xa6, 0xee, 0xc4, 0x73, 0x30, 0xca, 0x56, 0xdd,
	0x19, 0x3b, 0xbe, 0xf3, 0x80, 0x40, 0xb2, 0xc9, 0x12, 0xb1, 0xd1, 0x50, 0xc3, 0x4e, 0xd2, 0x1f,
	0xc3, 0xa3, 0x15, 0x7f, 0x32, 0xd0, 0xef, 0xf0, 0xf9, 0x92, 0xe2, 0xf0, 0x3d, 0xbf, 0x99, 0xfb,
	0xc2, 0xb9, 0x43, 0x0a, 0xa7, 0x5a, 0xfc, 0x31, 0x9c, 0x3b, 0x35, 0x32, 0x77, 0x5f, 0x07, 0x43,
	0x93, 0xa4, 0x89, 0xd6, 0xc4, 0x44, 0x8b, 0x50, 0x91, 0xb9, 0xd6, 0x77, 0xe0, 0xe9, 0xad, 0xf1,
	0x25, 0xbd, 0x11, 0x3c, 0x59, 0x51, 0x9f, 0x1a, 0xb5, 0x0f, 0x2b, 0x46, 0xc8, 0x44, 0x5d, 0xcf,
	0x64, 0x3b, 0x56, 0x09, 0x0a, 0x25, 0x89, 0xfc, 0x1c, 0xd3, 0x9e, 0xb7, 0x0c, 0xf3, 0x1e, 0x26,
	0xfc, 0x12, 0x12, 0x8b, 0x71, 0x7e, 0x28, 0x93, 0x78, 0x4d, 0x44, 0x2c, 0x49, 0xe5, 0x2a, 0xa6,
	0xa6, 0xe9, 0xbb, 0x87, 0x8b, 0x3f, 0x0a, 0xef, 0xcc, 0xff, 0x00, 0x2e, 0xcf, 0x60, 0xfb, 0xf6,
	0x60, 0x92, 0xcc, 0x9f, 0x0a, 0xec, 0xc4, 0xcb, 0xf6, 0x90, 0x1e, 0x8a, 0xb5, 0x2c, 0xef, 0x2a,
	0x35, 0xde, 0x55, 0xc9, 0xdb, 0xba, 0x2a, 0xb5, 0x9e, 0x75, 0x15, 0x9e, 0xdd, 0x45, 0x4a, 0xf2,
	0xfe, 0x4b, 0x89, 0x99, 0xf0, 0x22, 0x3f, 0x80, 0xf8, 0xca, 0xa5, 0x7e, 0x5a, 0xe2, 0xbb, 0xf0,
	0xfc, 0x4e, 0x56, 0x92, 0xf9, 0x1f, 0xca, 0xad, 0x36, 0x0f, 0xe9, 0x81, 0x38, 0x75, 0x7f, 0x14,
	0x52, 0x5f, 0xea, 0x8a, 0x7b, 0xa6, 0x56, 0x87, 0xea, 0xdd, 0x14, 0x24, 0xcf, 0x13, 0x28, 0x1f,
	0x3b, 0xfe, 0x27, 0x7a, 0x7f, 0xbd, 0x01, 0x16, 0x75, 0x26, 0x42, 0x44, 0x5f, 0xb1, 0xca, 0x9a,
	0x57, 0xec, 0x97, 0x50, 0x3a, 0x75, 0x31, 0x92, 0x3b, 0x5b, 0x43, 0x43, 0xff, 0x0d, 0x36, 0x42,
	0x2b, 0xe9, 0xff, 0xe3, 0x5f, 0xeb, 0xec, 0x25, 0xe4, 0xdc, 0xa9, 0x33, 0xa3, 0x5d, 0x40, 0xce,
	0xd8, 0x86, 0xa8, 0x66, 0x3b, 0x80, 0xad, 0x85, 0x85, 0xde, 0x04, 0xd6, 0xc5, 0xfc, 0x2e, 0x9d,
	0xde, 0xe8, 0xda, 0x59, 0x47, 0x93, 0x3d, 0x87, 0x7c, 0xff, 0xd2, 0xb1, 0x3d, 0x67, 0xe0, 0x4e,
	0x86, 0x9e, 0x1c, 0x69, 0x40, 0xa8, 0x2b, 0x10, 0xfd, 0x11, 0x6c, 0x2e, 0xb9, 0x92, 0xd7, 0xf1,
	0x42, 0x54, 0xf0, 0xfe, 0x08, 0xfa, 0x6b, 0xd8, 0x3c, 0x8e, 0x3b, 0x58, 0x0d, 0xac, 0xc4, 0x02,
	0xef, 0x42, 0xbe, 0x35, 0xf2, 0xd6, 0x8d, 0x8f, 0xfe, 0x2d, 0x14, 0x84, 0x49, 0xe8, 0x33, 0x39,
	0x46, 0x19, 0x6d, 0xd4, 0xd5, 0x4a, 0x92, 0x42, 0xff, 0x07, 0x97, 0xc4, 0xae, 0xd8, 0xa8, 0xd8,
	0x37, 0xcb, 0x4b, 0x62, 0x59, 0x94, 0xb3, 0xbb, 0xd8, 0xb7, 0x82, 0xd5, 0xec, 0x31, 0x64, 0x68,
	0xb9, 0x09, 0x9b, 0x2a, 0xcd, 0x37, 0x1b, 0xec, 0xab, 0x2a, 0x14, 0xa4, 0x42, 0xfc, 0x83, 0x17,
	0x7b, 0x19, 0x08, 0x6d, 0x74, 0x07, 0x4b, 0xde, 0xbe, 0x83, 0xa5, 0x96, 0x76, 0x30, 0xfd, 0x1a,
	0xca, 0x32, 0x3a, 0x92, 0x5e, 0x77, 0x67, 0x3b, 0x00, 0xc1, 0xae, 0x18, 0xbe, 0x85, 0x73, 0x12,
	0xc1, 0x6d, 0x05, 0x5b, 0x4a, 0x0a, 0xc4, 0x48, 0x16, 0x42, 0xba, 0xb6, 0x02, 0x9d, 0x7e, 0x80,
	0x3d, 0x12, 0x09, 0x27, 0x4b, 0xb8, 0xec, 0x5b, 0x59, 0xf1, 0x8d, 0x8d, 0xb5, 0x25, 0x0f, 0x89,
	0x81, 0xfd, 0x78, 0x9a, 0x7c, 0x87, 0x58, 0x71, 0x25, 0x5b, 0xeb, 0x28, 0xac, 0x03, 0xf6, 0xcd,
	0xff, 0x08, 0xf0, 0x26, 0x4c, 0x90, 0xfc, 0x2c, 0x86, 0x3c, 0xa8, 0x8e, 0x72, 0x77, 0x75, 0xf6,
	0x6e, 0x14, 0x48, 0x8b, 0x4f, 0x06, 0xbc, 0xc4, 0xc2, 0x51, 0xcb, 0x38, 0xb6, 0xcf, 0xcc, 0x13,
	0xb3, 0xfd, 0xd6, 0xd4, 0x3e, 0xc3, 0x7d, 0x50, 0x23, 0xa4, 0xde, 0xec, 0xd6, 0x0c, 0xab, 0x6e,
	0x77, 0xad, 0x9a, 0x96, 0x88, 0xa1, 0xf5, 0x6e, 0x4f, 0x4b, 0xb2, 0x32, 0x14, 0x09, 0x6d, 0x1d,
	0xb4, 0xda, 0xed, 0x93, 0xb3, 0x8e, 0xa6, 0xb1, 0x0d, 0xc8, 0x13, 0xd4, 0xed, 0x19, 0xbd, 0x66,
	0x4d, 0xab, 0xe2, 0xc9, 0x12, 0x01, 0xa7, 0xed, 0xf3, 0x86, 0xdd, 0x69, 0x5b, 0x3d, 0xed, 0xe6,
	0xe6, 0xfb, 0xbd, 0x1f, 0x71, 0x00, 0x16, 0xe3, 0xcd, 0x00, 0xd2, 0xf5, 0x46, 0xab, 0xd1, 0x6b,
	0x20, 0x81, 0x0c, 0xa8, 0x46, 0xbd, 0xae, 0x29, 0x1c, 0xb4, 0x1a, 0x74, 0x22, 0xc1, 0xdd, 0xb6,
	0x1a, 0x86, 0x65, 0xda, 0x8d, 0xf3, 0x86, 0xd9, 0xd3, 0x54, 0x56, 0x84, 0x9c, 0x71, 0xdc, 0x90,
	0x62, 0x92, 0x95, 0x00, 0x28, 0x80, 0x90, 0x53, 0x7b, 0x2f, 0xb9, 0x7f, 0xfa, 0x34, 0xa1, 0x34,
	0xd1, 0x67, 0xad, 0x73, 0x86, 0xce, 0xf3, 0x90, 0x91, 0x29, 0x60, 0x80, 0x2c, 0x24, 0x0f, 0x3b,
	0xf5, 0x33, 0x4d, 0xdb, 0xbb, 0xc0, 0x61, 0x8b, 0xbc, 0xbb, 0xf1, 0x46, 0x4a, 0x82, 0x4f, 0xa4,
	0x30, 0x98, 0xac, 0xc4, 0x64, 0x6e, 0x4a, 0xc4, 0xac, 0xd3, 0x30, 0xeb, 0x4d, 0xf3, 0x18, 0x99,
	0x3e, 0x86, 0x4d, 0x89, 0x99, 0x6d, 0xbb, 0x66, 0xb4, 0x5a, 0x87, 0x46, 0xed, 0xa4, 0xab, 0xa9,
	0x7b, 0x1e, 0x14, 0x97, 0x46, 0x90, 0x6d, 0xc2, 0x06, 0x79, 0x6a, 0x9b, 0x91, 0x28, 0x11, 0xf0,
	0x6d, 0xb3, 0xf7, 0x83, 0xdd, 0xe4, 0x44, 0xf1, 0x96, 0x02, 0xb0, 0xd9, 0x39, 0xff, 0x0e, 0xa3,
	0x2c, 0x23, 0xaf, 0xb1, 0x02, 0x78, 0x43, 0x01, 0x62, 0x58, 0x1d, 0xdb, 0xc2, 0x3f, 0x5a, 0xf6,
	0x22, 0x4d, 0x1f, 0x91, 0x07, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x15, 0x2f, 0x0e, 0x50,
	0x0e, 0x00, 0x00,
}
