// Code generated by protoc-gen-go.
// source: proto/knet.proto
// DO NOT EDIT!

/*
Package knet is a generated protocol buffer package.

It is generated from these files:
	proto/knet.proto

It has these top-level messages:
	NetIF
	InitKNETRequest
	InitKNETResponse
	AddKNETRequest
	AddKNETResponse
	DeleteKNETRequest
	DeleteKNETResponse
	ListKNETRequest
	ListKNETResponse
*/
package knet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NetIF struct {
	Name []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port int64  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *NetIF) Reset()                    { *m = NetIF{} }
func (m *NetIF) String() string            { return proto.CompactTextString(m) }
func (*NetIF) ProtoMessage()               {}
func (*NetIF) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NetIF) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *NetIF) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type InitKNETRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
}

func (m *InitKNETRequest) Reset()                    { *m = InitKNETRequest{} }
func (m *InitKNETRequest) String() string            { return proto.CompactTextString(m) }
func (*InitKNETRequest) ProtoMessage()               {}
func (*InitKNETRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InitKNETRequest) GetUnit() int64 {
	if m != nil {
		return m.Unit
	}
	return 0
}

type InitKNETResponse struct {
}

func (m *InitKNETResponse) Reset()                    { *m = InitKNETResponse{} }
func (m *InitKNETResponse) String() string            { return proto.CompactTextString(m) }
func (*InitKNETResponse) ProtoMessage()               {}
func (*InitKNETResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type AddKNETRequest struct {
	Unit  int64  `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Netif *NetIF `protobuf:"bytes,2,opt,name=netif" json:"netif,omitempty"`
}

func (m *AddKNETRequest) Reset()                    { *m = AddKNETRequest{} }
func (m *AddKNETRequest) String() string            { return proto.CompactTextString(m) }
func (*AddKNETRequest) ProtoMessage()               {}
func (*AddKNETRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddKNETRequest) GetUnit() int64 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *AddKNETRequest) GetNetif() *NetIF {
	if m != nil {
		return m.Netif
	}
	return nil
}

type AddKNETResponse struct {
	Id       int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FilterId int64 `protobuf:"varint,2,opt,name=filter_id,json=filterId" json:"filter_id,omitempty"`
}

func (m *AddKNETResponse) Reset()                    { *m = AddKNETResponse{} }
func (m *AddKNETResponse) String() string            { return proto.CompactTextString(m) }
func (*AddKNETResponse) ProtoMessage()               {}
func (*AddKNETResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddKNETResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddKNETResponse) GetFilterId() int64 {
	if m != nil {
		return m.FilterId
	}
	return 0
}

type DeleteKNETRequest struct {
	Unit     int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Id       int64 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	FilterId int64 `protobuf:"varint,3,opt,name=filter_id,json=filterId" json:"filter_id,omitempty"`
}

func (m *DeleteKNETRequest) Reset()                    { *m = DeleteKNETRequest{} }
func (m *DeleteKNETRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteKNETRequest) ProtoMessage()               {}
func (*DeleteKNETRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteKNETRequest) GetUnit() int64 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *DeleteKNETRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteKNETRequest) GetFilterId() int64 {
	if m != nil {
		return m.FilterId
	}
	return 0
}

type DeleteKNETResponse struct {
}

func (m *DeleteKNETResponse) Reset()                    { *m = DeleteKNETResponse{} }
func (m *DeleteKNETResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteKNETResponse) ProtoMessage()               {}
func (*DeleteKNETResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ListKNETRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
}

func (m *ListKNETRequest) Reset()                    { *m = ListKNETRequest{} }
func (m *ListKNETRequest) String() string            { return proto.CompactTextString(m) }
func (*ListKNETRequest) ProtoMessage()               {}
func (*ListKNETRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListKNETRequest) GetUnit() int64 {
	if m != nil {
		return m.Unit
	}
	return 0
}

type ListKNETResponse struct {
	List []*NetIF `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ListKNETResponse) Reset()                    { *m = ListKNETResponse{} }
func (m *ListKNETResponse) String() string            { return proto.CompactTextString(m) }
func (*ListKNETResponse) ProtoMessage()               {}
func (*ListKNETResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListKNETResponse) GetList() []*NetIF {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*NetIF)(nil), "knet.NetIF")
	proto.RegisterType((*InitKNETRequest)(nil), "knet.InitKNETRequest")
	proto.RegisterType((*InitKNETResponse)(nil), "knet.InitKNETResponse")
	proto.RegisterType((*AddKNETRequest)(nil), "knet.AddKNETRequest")
	proto.RegisterType((*AddKNETResponse)(nil), "knet.AddKNETResponse")
	proto.RegisterType((*DeleteKNETRequest)(nil), "knet.DeleteKNETRequest")
	proto.RegisterType((*DeleteKNETResponse)(nil), "knet.DeleteKNETResponse")
	proto.RegisterType((*ListKNETRequest)(nil), "knet.ListKNETRequest")
	proto.RegisterType((*ListKNETResponse)(nil), "knet.ListKNETResponse")
}

func init() { proto.RegisterFile("proto/knet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcd, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xc9, 0x47, 0x45, 0xa7, 0xd2, 0xc4, 0xc1, 0x43, 0xc1, 0x83, 0x75, 0xa1, 0xd0, 0x53,
	0x0b, 0xf6, 0x2e, 0x08, 0x7e, 0x10, 0x94, 0x1e, 0x96, 0xde, 0x45, 0xd9, 0x29, 0x0c, 0xc6, 0x4d,
	0xcc, 0x4e, 0xff, 0x7f, 0xc9, 0x24, 0x58, 0x29, 0x42, 0x6e, 0x8f, 0x99, 0x37, 0xbf, 0x7d, 0x33,
	0x0b, 0x79, 0xdd, 0x54, 0x52, 0xad, 0x3e, 0x3d, 0xc9, 0x52, 0x25, 0xa6, 0xad, 0x36, 0x2b, 0x18,
	0x6d, 0x48, 0x8a, 0x27, 0x44, 0x48, 0xfd, 0xfb, 0x17, 0x4d, 0xa3, 0x59, 0xb4, 0x38, 0xb7, 0xaa,
	0xdb, 0x5a, 0x5d, 0x35, 0x32, 0x8d, 0x67, 0xd1, 0x22, 0xb1, 0xaa, 0xcd, 0x1c, 0xb2, 0xc2, 0xb3,
	0xbc, 0x6c, 0x1e, 0xb7, 0x96, 0xbe, 0xf7, 0x14, 0xa4, 0xb5, 0xed, 0x3d, 0x8b, 0x8e, 0x26, 0x56,
	0xb5, 0x41, 0xc8, 0x0f, 0xb6, 0x50, 0x57, 0x3e, 0x90, 0x79, 0x86, 0xc9, 0xbd, 0x73, 0x03, 0x93,
	0x78, 0x03, 0x23, 0x4f, 0xc2, 0x3b, 0x7d, 0x75, 0x7c, 0x3b, 0x5e, 0x6a, 0x66, 0x0d, 0x69, 0xbb,
	0x8e, 0xb9, 0x83, 0xec, 0x17, 0xd4, 0xb1, 0x71, 0x02, 0x31, 0xbb, 0x9e, 0x13, 0xb3, 0xc3, 0x2b,
	0x38, 0xdb, 0x71, 0x29, 0xd4, 0xbc, 0xb1, 0xeb, 0xf3, 0x9f, 0x76, 0x85, 0xc2, 0x99, 0x2d, 0x5c,
	0x3c, 0x50, 0x49, 0x42, 0x43, 0x59, 0x3a, 0x6a, 0xfc, 0x3f, 0x35, 0x39, 0xa2, 0x5e, 0x02, 0xfe,
	0xa5, 0xf6, 0x4b, 0xcf, 0x21, 0x7b, 0xe5, 0x30, 0x78, 0xaf, 0x35, 0xe4, 0x07, 0x5b, 0xbf, 0xd3,
	0x35, 0xa4, 0x25, 0x87, 0xd6, 0x97, 0x1c, 0x1f, 0x42, 0x1b, 0x1f, 0x27, 0xfa, 0x93, 0xeb, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xfa, 0x77, 0x5f, 0xdd, 0x01, 0x00, 0x00,
}
