// Code generated by protoc-gen-go.
// source: port.proto
// DO NOT EDIT!

/*
Package port is a generated protocol buffer package.

It is generated from these files:
	port.proto

It has these top-level messages:
	Ability
	PortConfig
	PortInfo
	InitRequest
	InitResponse
	ClearRequest
	ClearResponse
	ProbeRequest
	ProbeResponse
	DetachRequest
	DetachResponse
	GetConfigRequest
	GetConfigResponse
	GetPortNameRequest
	GetPortNameResponse
	PortEnableSetRequest
	PortEnableSetResponse
	PortEnableGetRequest
	PortEnableGetResponse
	PortAdvertSetRequest
	PortAdvertSetResponse
	PortAdvertGetRequest
	PortAdvertGetResponse
	PortAbilityAdvertSetRequest
	PortAbilityAdvertSetResponse
	PortAbilityAdvertGetRequest
	PortAbilityAdvertGetResponse
	PortAdvertRemoteGetRequest
	PortAdvertRemoteGetResponse
	PortAbilityRemoteGetRequest
	PortAbilityRemoteGetResponse
	PortAbilityGetRequest
	PortAbilityGetResponse
	PortAbilityLocalGetRequest
	PortAbilityLocalGetResponse
	PortLinkscanSetRequest
	PortLinkscanSetResponse
	PortLinkscanGetRequest
	PortLinkscanGetResponse
	PortAutonegSetRequest
	PortAutonegSetResponse
	PortAutonegGetRequest
	PortAutonegGetResponse
	PortSpeedMAXRequest
	PortSpeedMAXResponse
	PortSpeedSetRequest
	PortSpeedSetResponse
	PortSpeedGetRequest
	PortSpeedGetResponse
	PortInterfaceSetRequest
	PortInterfaceSetResponse
	PortInterfaceGetRequest
	PortInterfaceGetResponse
	PortLinkStatusGetRequest
	PortLinkStatusGetResponse
	PortLinkFailedClearRequest
	PortLinkFailedClearResponse
	PortControlSetRequest
	PortControlSetResponse
	PortControlGetRequest
	PortControlGetResponse
	PortGportGetRequest
	PortGportGetResponse
	PortLocalGetRequest
	PortLocalGetResponse
*/
package port

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InterfaceType int32

const (
	InterfaceType_IF_TYPE_NOCXN           InterfaceType = 0
	InterfaceType_IF_TYPE_NULL            InterfaceType = 1
	InterfaceType_IF_TYPE_MII             InterfaceType = 2
	InterfaceType_IF_TYPE_GMII            InterfaceType = 3
	InterfaceType_IF_TYPE_SGMII           InterfaceType = 4
	InterfaceType_IF_TYPE_TBI             InterfaceType = 5
	InterfaceType_IF_TYPE_XGMII           InterfaceType = 6
	InterfaceType_IF_TYPE_RGMII           InterfaceType = 7
	InterfaceType_IF_TYPE_RvMII           InterfaceType = 8
	InterfaceType_IF_TYPE_SFI             InterfaceType = 9
	InterfaceType_IF_TYPE_XFI             InterfaceType = 10
	InterfaceType_IF_TYPE_KR              InterfaceType = 11
	InterfaceType_IF_TYPE_KR4             InterfaceType = 12
	InterfaceType_IF_TYPE_CR              InterfaceType = 13
	InterfaceType_IF_TYPE_CR4             InterfaceType = 14
	InterfaceType_IF_TYPE_XLAUI           InterfaceType = 15
	InterfaceType_IF_TYPE_SR              InterfaceType = 16
	InterfaceType_IF_TYPE_RXAUI           InterfaceType = 17
	InterfaceType_IF_TYPE_XAUI            InterfaceType = 18
	InterfaceType_IF_TYPE_SPAUI           InterfaceType = 19
	InterfaceType_IF_TYPE_QSGMII          InterfaceType = 20
	InterfaceType_IF_TYPE_ILKN            InterfaceType = 21
	InterfaceType_IF_TYPE_RCY             InterfaceType = 22
	InterfaceType_IF_TYPE_FAT_PIPE        InterfaceType = 23
	InterfaceType_IF_TYPE_CGMII           InterfaceType = 24
	InterfaceType_IF_TYPE_CAUI            InterfaceType = 25
	InterfaceType_IF_TYPE_LR              InterfaceType = 26
	InterfaceType_IF_TYPE_LR4             InterfaceType = 27
	InterfaceType_IF_TYPE_SR4             InterfaceType = 28
	InterfaceType_IF_TYPE_KX              InterfaceType = 29
	InterfaceType_IF_TYPE_ZR              InterfaceType = 30
	InterfaceType_IF_TYPE_SR10            InterfaceType = 31
	InterfaceType_IF_TYPE_OTL             InterfaceType = 32
	InterfaceType_IF_TYPE_CPU             InterfaceType = 33
	InterfaceType_IF_TYPE_OLP             InterfaceType = 34
	InterfaceType_IF_TYPE_OAMP            InterfaceType = 35
	InterfaceType_IF_TYPE_ERP             InterfaceType = 36
	InterfaceType_IF_TYPE_TM_INTERNAL_PKT InterfaceType = 37
	InterfaceType_IF_TYPE_SR2             InterfaceType = 38
	InterfaceType_IF_TYPE_KR2             InterfaceType = 39
	InterfaceType_IF_TYPE_CR2             InterfaceType = 40
	InterfaceType_IF_TYPE_XFI2            InterfaceType = 41
	InterfaceType_IF_TYPE_XLAUI2          InterfaceType = 42
	InterfaceType_IF_TYPE_CR10            InterfaceType = 43
	InterfaceType_IF_TYPE_KR10            InterfaceType = 44
	InterfaceType_IF_TYPE_LR10            InterfaceType = 45
	InterfaceType_IF_TYPE_ER              InterfaceType = 46
	InterfaceType_IF_TYPE_ER2             InterfaceType = 47
	InterfaceType_IF_TYPE_ER4             InterfaceType = 48
	InterfaceType_IF_TYPE_CX              InterfaceType = 49
	InterfaceType_IF_TYPE_CX2             InterfaceType = 50
	InterfaceType_IF_TYPE_CX4             InterfaceType = 51
	InterfaceType_IF_TYPE_CAUI_C2C        InterfaceType = 52
	InterfaceType_IF_TYPE_CAUI_C2M        InterfaceType = 53
	InterfaceType_IF_TYPE_VSR             InterfaceType = 54
	InterfaceType_IF_TYPE_LR2             InterfaceType = 55
	InterfaceType_IF_TYPE_LRM             InterfaceType = 56
	InterfaceType_IF_TYPE_XLPPI           InterfaceType = 57
	InterfaceType_IF_TYPE_COUNT           InterfaceType = 58
)

var InterfaceType_name = map[int32]string{
	0:  "IF_TYPE_NOCXN",
	1:  "IF_TYPE_NULL",
	2:  "IF_TYPE_MII",
	3:  "IF_TYPE_GMII",
	4:  "IF_TYPE_SGMII",
	5:  "IF_TYPE_TBI",
	6:  "IF_TYPE_XGMII",
	7:  "IF_TYPE_RGMII",
	8:  "IF_TYPE_RvMII",
	9:  "IF_TYPE_SFI",
	10: "IF_TYPE_XFI",
	11: "IF_TYPE_KR",
	12: "IF_TYPE_KR4",
	13: "IF_TYPE_CR",
	14: "IF_TYPE_CR4",
	15: "IF_TYPE_XLAUI",
	16: "IF_TYPE_SR",
	17: "IF_TYPE_RXAUI",
	18: "IF_TYPE_XAUI",
	19: "IF_TYPE_SPAUI",
	20: "IF_TYPE_QSGMII",
	21: "IF_TYPE_ILKN",
	22: "IF_TYPE_RCY",
	23: "IF_TYPE_FAT_PIPE",
	24: "IF_TYPE_CGMII",
	25: "IF_TYPE_CAUI",
	26: "IF_TYPE_LR",
	27: "IF_TYPE_LR4",
	28: "IF_TYPE_SR4",
	29: "IF_TYPE_KX",
	30: "IF_TYPE_ZR",
	31: "IF_TYPE_SR10",
	32: "IF_TYPE_OTL",
	33: "IF_TYPE_CPU",
	34: "IF_TYPE_OLP",
	35: "IF_TYPE_OAMP",
	36: "IF_TYPE_ERP",
	37: "IF_TYPE_TM_INTERNAL_PKT",
	38: "IF_TYPE_SR2",
	39: "IF_TYPE_KR2",
	40: "IF_TYPE_CR2",
	41: "IF_TYPE_XFI2",
	42: "IF_TYPE_XLAUI2",
	43: "IF_TYPE_CR10",
	44: "IF_TYPE_KR10",
	45: "IF_TYPE_LR10",
	46: "IF_TYPE_ER",
	47: "IF_TYPE_ER2",
	48: "IF_TYPE_ER4",
	49: "IF_TYPE_CX",
	50: "IF_TYPE_CX2",
	51: "IF_TYPE_CX4",
	52: "IF_TYPE_CAUI_C2C",
	53: "IF_TYPE_CAUI_C2M",
	54: "IF_TYPE_VSR",
	55: "IF_TYPE_LR2",
	56: "IF_TYPE_LRM",
	57: "IF_TYPE_XLPPI",
	58: "IF_TYPE_COUNT",
}
var InterfaceType_value = map[string]int32{
	"IF_TYPE_NOCXN":           0,
	"IF_TYPE_NULL":            1,
	"IF_TYPE_MII":             2,
	"IF_TYPE_GMII":            3,
	"IF_TYPE_SGMII":           4,
	"IF_TYPE_TBI":             5,
	"IF_TYPE_XGMII":           6,
	"IF_TYPE_RGMII":           7,
	"IF_TYPE_RvMII":           8,
	"IF_TYPE_SFI":             9,
	"IF_TYPE_XFI":             10,
	"IF_TYPE_KR":              11,
	"IF_TYPE_KR4":             12,
	"IF_TYPE_CR":              13,
	"IF_TYPE_CR4":             14,
	"IF_TYPE_XLAUI":           15,
	"IF_TYPE_SR":              16,
	"IF_TYPE_RXAUI":           17,
	"IF_TYPE_XAUI":            18,
	"IF_TYPE_SPAUI":           19,
	"IF_TYPE_QSGMII":          20,
	"IF_TYPE_ILKN":            21,
	"IF_TYPE_RCY":             22,
	"IF_TYPE_FAT_PIPE":        23,
	"IF_TYPE_CGMII":           24,
	"IF_TYPE_CAUI":            25,
	"IF_TYPE_LR":              26,
	"IF_TYPE_LR4":             27,
	"IF_TYPE_SR4":             28,
	"IF_TYPE_KX":              29,
	"IF_TYPE_ZR":              30,
	"IF_TYPE_SR10":            31,
	"IF_TYPE_OTL":             32,
	"IF_TYPE_CPU":             33,
	"IF_TYPE_OLP":             34,
	"IF_TYPE_OAMP":            35,
	"IF_TYPE_ERP":             36,
	"IF_TYPE_TM_INTERNAL_PKT": 37,
	"IF_TYPE_SR2":             38,
	"IF_TYPE_KR2":             39,
	"IF_TYPE_CR2":             40,
	"IF_TYPE_XFI2":            41,
	"IF_TYPE_XLAUI2":          42,
	"IF_TYPE_CR10":            43,
	"IF_TYPE_KR10":            44,
	"IF_TYPE_LR10":            45,
	"IF_TYPE_ER":              46,
	"IF_TYPE_ER2":             47,
	"IF_TYPE_ER4":             48,
	"IF_TYPE_CX":              49,
	"IF_TYPE_CX2":             50,
	"IF_TYPE_CX4":             51,
	"IF_TYPE_CAUI_C2C":        52,
	"IF_TYPE_CAUI_C2M":        53,
	"IF_TYPE_VSR":             54,
	"IF_TYPE_LR2":             55,
	"IF_TYPE_LRM":             56,
	"IF_TYPE_XLPPI":           57,
	"IF_TYPE_COUNT":           58,
}

func (x InterfaceType) String() string {
	return proto.EnumName(InterfaceType_name, int32(x))
}
func (InterfaceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ControlType int32

const (
	ControlType_CONTROL_TYPE_UNKNOWN                     ControlType = 0
	ControlType_CONTROL_TYPE_IP4                         ControlType = 8
	ControlType_CONTROL_TYPE_IP6                         ControlType = 9
	ControlType_CONTROL_TYPE_TRUST_INCOMING_VLAN         ControlType = 22
	ControlType_CONTROL_TYPE_DO_NOT_CHECK_VLAN           ControlType = 23
	ControlType_CONTROL_TYPE_EGREE_VLAN_PRI_USES_PKT_PRI ControlType = 43
	ControlType_CONTROL_TYPE_CONTROL_LANES               ControlType = 55
	ControlType_CONTROL_TYPE_PFC_RECEIVE                 ControlType = 59
	ControlType_CONTROL_TYPE_PFC_TRANSMIT                ControlType = 60
	ControlType_CONTROL_TYPE_PFC_CLASSES                 ControlType = 61
	ControlType_CONTROL_TYPE_PFC_PASS_FRAMES             ControlType = 62
	ControlType_CONTROL_TYPE_L2_MOVE                     ControlType = 70
	ControlType_CONTROL_TYPE_STAT_OVERSIZE               ControlType = 92
	ControlType_CONTROL_TYPE_VXLAN_ENABLE                ControlType = 187
	ControlType_CONTROL_TYPE_VXLAN_TUNNEL_BASED_VNID     ControlType = 188
	ControlType_CONTROL_TYPE_VXLAN_DEFAULT_TUNNEL_ENABLE ControlType = 189
	ControlType_CONTROL_TYPE_SAMPLE_INGRESS_DEST         ControlType = 304
)

var ControlType_name = map[int32]string{
	0:   "CONTROL_TYPE_UNKNOWN",
	8:   "CONTROL_TYPE_IP4",
	9:   "CONTROL_TYPE_IP6",
	22:  "CONTROL_TYPE_TRUST_INCOMING_VLAN",
	23:  "CONTROL_TYPE_DO_NOT_CHECK_VLAN",
	43:  "CONTROL_TYPE_EGREE_VLAN_PRI_USES_PKT_PRI",
	55:  "CONTROL_TYPE_CONTROL_LANES",
	59:  "CONTROL_TYPE_PFC_RECEIVE",
	60:  "CONTROL_TYPE_PFC_TRANSMIT",
	61:  "CONTROL_TYPE_PFC_CLASSES",
	62:  "CONTROL_TYPE_PFC_PASS_FRAMES",
	70:  "CONTROL_TYPE_L2_MOVE",
	92:  "CONTROL_TYPE_STAT_OVERSIZE",
	187: "CONTROL_TYPE_VXLAN_ENABLE",
	188: "CONTROL_TYPE_VXLAN_TUNNEL_BASED_VNID",
	189: "CONTROL_TYPE_VXLAN_DEFAULT_TUNNEL_ENABLE",
	304: "CONTROL_TYPE_SAMPLE_INGRESS_DEST",
}
var ControlType_value = map[string]int32{
	"CONTROL_TYPE_UNKNOWN":                     0,
	"CONTROL_TYPE_IP4":                         8,
	"CONTROL_TYPE_IP6":                         9,
	"CONTROL_TYPE_TRUST_INCOMING_VLAN":         22,
	"CONTROL_TYPE_DO_NOT_CHECK_VLAN":           23,
	"CONTROL_TYPE_EGREE_VLAN_PRI_USES_PKT_PRI": 43,
	"CONTROL_TYPE_CONTROL_LANES":               55,
	"CONTROL_TYPE_PFC_RECEIVE":                 59,
	"CONTROL_TYPE_PFC_TRANSMIT":                60,
	"CONTROL_TYPE_PFC_CLASSES":                 61,
	"CONTROL_TYPE_PFC_PASS_FRAMES":             62,
	"CONTROL_TYPE_L2_MOVE":                     70,
	"CONTROL_TYPE_STAT_OVERSIZE":               92,
	"CONTROL_TYPE_VXLAN_ENABLE":                187,
	"CONTROL_TYPE_VXLAN_TUNNEL_BASED_VNID":     188,
	"CONTROL_TYPE_VXLAN_DEFAULT_TUNNEL_ENABLE": 189,
	"CONTROL_TYPE_SAMPLE_INGRESS_DEST":         304,
}

func (x ControlType) String() string {
	return proto.EnumName(ControlType_name, int32(x))
}
func (ControlType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Ability struct {
	SpeedHalfDuplex uint64 `protobuf:"varint,1,opt,name=speed_half_duplex,json=speedHalfDuplex" json:"speed_half_duplex,omitempty"`
	SpeedFullDuplex uint64 `protobuf:"varint,2,opt,name=speed_full_duplex,json=speedFullDuplex" json:"speed_full_duplex,omitempty"`
	Pause           uint64 `protobuf:"varint,3,opt,name=pause" json:"pause,omitempty"`
	Interface       uint64 `protobuf:"varint,4,opt,name=interface" json:"interface,omitempty"`
	Medium          uint64 `protobuf:"varint,5,opt,name=medium" json:"medium,omitempty"`
	Loopback        uint64 `protobuf:"varint,6,opt,name=loopback" json:"loopback,omitempty"`
	Flags           uint64 `protobuf:"varint,7,opt,name=flags" json:"flags,omitempty"`
	Eee             uint64 `protobuf:"varint,8,opt,name=eee" json:"eee,omitempty"`
	Fcmap           uint64 `protobuf:"varint,9,opt,name=fcmap" json:"fcmap,omitempty"`
	//    encap = 10;
	Fec uint64 `protobuf:"varint,11,opt,name=fec" json:"fec,omitempty"`
}

func (m *Ability) Reset()                    { *m = Ability{} }
func (m *Ability) String() string            { return proto.CompactTextString(m) }
func (*Ability) ProtoMessage()               {}
func (*Ability) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PortConfig struct {
	Fe         []uint32 `protobuf:"varint,1,rep,name=fe" json:"fe,omitempty"`
	Ge         []uint32 `protobuf:"varint,2,rep,name=ge" json:"ge,omitempty"`
	Xe         []uint32 `protobuf:"varint,3,rep,name=xe" json:"xe,omitempty"`
	Ce         []uint32 `protobuf:"varint,4,rep,name=ce" json:"ce,omitempty"`
	E          []uint32 `protobuf:"varint,5,rep,name=e" json:"e,omitempty"`
	Hg         []uint32 `protobuf:"varint,6,rep,name=hg" json:"hg,omitempty"`
	Sci        []uint32 `protobuf:"varint,7,rep,name=sci" json:"sci,omitempty"`
	Sfi        []uint32 `protobuf:"varint,8,rep,name=sfi" json:"sfi,omitempty"`
	Spi        []uint32 `protobuf:"varint,9,rep,name=spi" json:"spi,omitempty"`
	SpiSubport []uint32 `protobuf:"varint,10,rep,name=spi_subport,json=spiSubport" json:"spi_subport,omitempty"`
	Port       []uint32 `protobuf:"varint,11,rep,name=port" json:"port,omitempty"`
	Cpu        []uint32 `protobuf:"varint,12,rep,name=cpu" json:"cpu,omitempty"`
	All        []uint32 `protobuf:"varint,13,rep,name=all" json:"all,omitempty"`
	StackInt   []uint32 `protobuf:"varint,14,rep,name=stack_int,json=stackInt" json:"stack_int,omitempty"`
	StackExt   []uint32 `protobuf:"varint,15,rep,name=stack_ext,json=stackExt" json:"stack_ext,omitempty"`
	Tdm        []uint32 `protobuf:"varint,16,rep,name=tdm" json:"tdm,omitempty"`
	Pon        []uint32 `protobuf:"varint,17,rep,name=pon" json:"pon,omitempty"`
	Llid       []uint32 `protobuf:"varint,18,rep,name=llid" json:"llid,omitempty"`
	Xl         []uint32 `protobuf:"varint,19,rep,name=xl" json:"xl,omitempty"`
	Rcy        []uint32 `protobuf:"varint,20,rep,name=rcy" json:"rcy,omitempty"`
	//    opennsl_pbmp_t per_pipe[OPENNSL_PIPES_MAX]; /**< Mask of ports per pipe. The number of
	//                                           pipes per device can be obtained via
	//                                           num_pipes field of opennsl_info_t. */
	Nif     []uint32 `protobuf:"varint,22,rep,name=nif" json:"nif,omitempty"`
	Control []uint32 `protobuf:"varint,23,rep,name=control" json:"control,omitempty"`
}

func (m *PortConfig) Reset()                    { *m = PortConfig{} }
func (m *PortConfig) String() string            { return proto.CompactTextString(m) }
func (*PortConfig) ProtoMessage()               {}
func (*PortConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PortInfo struct {
	ActionMask       uint32 `protobuf:"varint,1,opt,name=action_mask,json=actionMask" json:"action_mask,omitempty"`
	ActionMask2      uint32 `protobuf:"varint,2,opt,name=action_mask2,json=actionMask2" json:"action_mask2,omitempty"`
	Enable           int64  `protobuf:"varint,3,opt,name=enable" json:"enable,omitempty"`
	LinkStatus       int64  `protobuf:"varint,4,opt,name=link_status,json=linkStatus" json:"link_status,omitempty"`
	AutoNeg          int64  `protobuf:"varint,5,opt,name=auto_neg,json=autoNeg" json:"auto_neg,omitempty"`
	Speed            int64  `protobuf:"varint,6,opt,name=speed" json:"speed,omitempty"`
	Duplex           int64  `protobuf:"varint,7,opt,name=duplex" json:"duplex,omitempty"`
	Linkscan         int64  `protobuf:"varint,8,opt,name=linkscan" json:"linkscan,omitempty"`
	Learn            uint32 `protobuf:"varint,9,opt,name=learn" json:"learn,omitempty"`
	Discard          int64  `protobuf:"varint,10,opt,name=discard" json:"discard,omitempty"`
	Vlanfilter       uint32 `protobuf:"varint,11,opt,name=vlanfilter" json:"vlanfilter,omitempty"`
	UntaggedPriority int64  `protobuf:"varint,12,opt,name=untagged_priority,json=untaggedPriority" json:"untagged_priority,omitempty"`
}

func (m *PortInfo) Reset()                    { *m = PortInfo{} }
func (m *PortInfo) String() string            { return proto.CompactTextString(m) }
func (*PortInfo) ProtoMessage()               {}
func (*PortInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type InitRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
}

func (m *InitRequest) Reset()                    { *m = InitRequest{} }
func (m *InitRequest) String() string            { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()               {}
func (*InitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type InitResponse struct {
}

func (m *InitResponse) Reset()                    { *m = InitResponse{} }
func (m *InitResponse) String() string            { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()               {}
func (*InitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ClearRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
}

func (m *ClearRequest) Reset()                    { *m = ClearRequest{} }
func (m *ClearRequest) String() string            { return proto.CompactTextString(m) }
func (*ClearRequest) ProtoMessage()               {}
func (*ClearRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ClearResponse struct {
}

func (m *ClearResponse) Reset()                    { *m = ClearResponse{} }
func (m *ClearResponse) String() string            { return proto.CompactTextString(m) }
func (*ClearResponse) ProtoMessage()               {}
func (*ClearResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ProbeRequest struct {
	Unit int64    `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Pbmp []uint32 `protobuf:"varint,2,rep,name=pbmp" json:"pbmp,omitempty"`
}

func (m *ProbeRequest) Reset()                    { *m = ProbeRequest{} }
func (m *ProbeRequest) String() string            { return proto.CompactTextString(m) }
func (*ProbeRequest) ProtoMessage()               {}
func (*ProbeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ProbeResponse struct {
	Pbmp []uint32 `protobuf:"varint,1,rep,name=pbmp" json:"pbmp,omitempty"`
}

func (m *ProbeResponse) Reset()                    { *m = ProbeResponse{} }
func (m *ProbeResponse) String() string            { return proto.CompactTextString(m) }
func (*ProbeResponse) ProtoMessage()               {}
func (*ProbeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type DetachRequest struct {
	Unit int64    `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Pbmp []uint32 `protobuf:"varint,2,rep,name=pbmp" json:"pbmp,omitempty"`
}

func (m *DetachRequest) Reset()                    { *m = DetachRequest{} }
func (m *DetachRequest) String() string            { return proto.CompactTextString(m) }
func (*DetachRequest) ProtoMessage()               {}
func (*DetachRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type DetachResponse struct {
	Pbmp []uint32 `protobuf:"varint,1,rep,name=pbmp" json:"pbmp,omitempty"`
}

func (m *DetachResponse) Reset()                    { *m = DetachResponse{} }
func (m *DetachResponse) String() string            { return proto.CompactTextString(m) }
func (*DetachResponse) ProtoMessage()               {}
func (*DetachResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type GetConfigRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
}

func (m *GetConfigRequest) Reset()                    { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()               {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type GetConfigResponse struct {
	Config *PortConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
}

func (m *GetConfigResponse) Reset()                    { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()               {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetConfigResponse) GetConfig() *PortConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type GetPortNameRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *GetPortNameRequest) Reset()                    { *m = GetPortNameRequest{} }
func (m *GetPortNameRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPortNameRequest) ProtoMessage()               {}
func (*GetPortNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type GetPortNameResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetPortNameResponse) Reset()                    { *m = GetPortNameResponse{} }
func (m *GetPortNameResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPortNameResponse) ProtoMessage()               {}
func (*GetPortNameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type PortEnableSetRequest struct {
	Unit   int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port   int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Enable bool  `protobuf:"varint,3,opt,name=enable" json:"enable,omitempty"`
}

func (m *PortEnableSetRequest) Reset()                    { *m = PortEnableSetRequest{} }
func (m *PortEnableSetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortEnableSetRequest) ProtoMessage()               {}
func (*PortEnableSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type PortEnableSetResponse struct {
}

func (m *PortEnableSetResponse) Reset()                    { *m = PortEnableSetResponse{} }
func (m *PortEnableSetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortEnableSetResponse) ProtoMessage()               {}
func (*PortEnableSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type PortEnableGetRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortEnableGetRequest) Reset()                    { *m = PortEnableGetRequest{} }
func (m *PortEnableGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortEnableGetRequest) ProtoMessage()               {}
func (*PortEnableGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type PortEnableGetResponse struct {
	Enable bool `protobuf:"varint,1,opt,name=enable" json:"enable,omitempty"`
}

func (m *PortEnableGetResponse) Reset()                    { *m = PortEnableGetResponse{} }
func (m *PortEnableGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortEnableGetResponse) ProtoMessage()               {}
func (*PortEnableGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type PortAdvertSetRequest struct {
	Unit    int64  `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port    int64  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Ability uint64 `protobuf:"varint,3,opt,name=ability" json:"ability,omitempty"`
}

func (m *PortAdvertSetRequest) Reset()                    { *m = PortAdvertSetRequest{} }
func (m *PortAdvertSetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortAdvertSetRequest) ProtoMessage()               {}
func (*PortAdvertSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type PortAdvertSetResponse struct {
}

func (m *PortAdvertSetResponse) Reset()                    { *m = PortAdvertSetResponse{} }
func (m *PortAdvertSetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortAdvertSetResponse) ProtoMessage()               {}
func (*PortAdvertSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type PortAdvertGetRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortAdvertGetRequest) Reset()                    { *m = PortAdvertGetRequest{} }
func (m *PortAdvertGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortAdvertGetRequest) ProtoMessage()               {}
func (*PortAdvertGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type PortAdvertGetResponse struct {
	Ability uint64 `protobuf:"varint,1,opt,name=ability" json:"ability,omitempty"`
}

func (m *PortAdvertGetResponse) Reset()                    { *m = PortAdvertGetResponse{} }
func (m *PortAdvertGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortAdvertGetResponse) ProtoMessage()               {}
func (*PortAdvertGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type PortAbilityAdvertSetRequest struct {
	Unit    int64    `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port    int64    `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Ability *Ability `protobuf:"bytes,3,opt,name=ability" json:"ability,omitempty"`
}

func (m *PortAbilityAdvertSetRequest) Reset()                    { *m = PortAbilityAdvertSetRequest{} }
func (m *PortAbilityAdvertSetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortAbilityAdvertSetRequest) ProtoMessage()               {}
func (*PortAbilityAdvertSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *PortAbilityAdvertSetRequest) GetAbility() *Ability {
	if m != nil {
		return m.Ability
	}
	return nil
}

type PortAbilityAdvertSetResponse struct {
}

func (m *PortAbilityAdvertSetResponse) Reset()                    { *m = PortAbilityAdvertSetResponse{} }
func (m *PortAbilityAdvertSetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortAbilityAdvertSetResponse) ProtoMessage()               {}
func (*PortAbilityAdvertSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type PortAbilityAdvertGetRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortAbilityAdvertGetRequest) Reset()                    { *m = PortAbilityAdvertGetRequest{} }
func (m *PortAbilityAdvertGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortAbilityAdvertGetRequest) ProtoMessage()               {}
func (*PortAbilityAdvertGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type PortAbilityAdvertGetResponse struct {
	Ability *Ability `protobuf:"bytes,1,opt,name=ability" json:"ability,omitempty"`
}

func (m *PortAbilityAdvertGetResponse) Reset()                    { *m = PortAbilityAdvertGetResponse{} }
func (m *PortAbilityAdvertGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortAbilityAdvertGetResponse) ProtoMessage()               {}
func (*PortAbilityAdvertGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *PortAbilityAdvertGetResponse) GetAbility() *Ability {
	if m != nil {
		return m.Ability
	}
	return nil
}

type PortAdvertRemoteGetRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortAdvertRemoteGetRequest) Reset()                    { *m = PortAdvertRemoteGetRequest{} }
func (m *PortAdvertRemoteGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortAdvertRemoteGetRequest) ProtoMessage()               {}
func (*PortAdvertRemoteGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type PortAdvertRemoteGetResponse struct {
	Ability uint64 `protobuf:"varint,3,opt,name=ability" json:"ability,omitempty"`
}

func (m *PortAdvertRemoteGetResponse) Reset()                    { *m = PortAdvertRemoteGetResponse{} }
func (m *PortAdvertRemoteGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortAdvertRemoteGetResponse) ProtoMessage()               {}
func (*PortAdvertRemoteGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type PortAbilityRemoteGetRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortAbilityRemoteGetRequest) Reset()                    { *m = PortAbilityRemoteGetRequest{} }
func (m *PortAbilityRemoteGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortAbilityRemoteGetRequest) ProtoMessage()               {}
func (*PortAbilityRemoteGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

type PortAbilityRemoteGetResponse struct {
	Ability *Ability `protobuf:"bytes,1,opt,name=ability" json:"ability,omitempty"`
}

func (m *PortAbilityRemoteGetResponse) Reset()                    { *m = PortAbilityRemoteGetResponse{} }
func (m *PortAbilityRemoteGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortAbilityRemoteGetResponse) ProtoMessage()               {}
func (*PortAbilityRemoteGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *PortAbilityRemoteGetResponse) GetAbility() *Ability {
	if m != nil {
		return m.Ability
	}
	return nil
}

type PortAbilityGetRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortAbilityGetRequest) Reset()                    { *m = PortAbilityGetRequest{} }
func (m *PortAbilityGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortAbilityGetRequest) ProtoMessage()               {}
func (*PortAbilityGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

type PortAbilityGetResponse struct {
	Ability uint64 `protobuf:"varint,1,opt,name=ability" json:"ability,omitempty"`
}

func (m *PortAbilityGetResponse) Reset()                    { *m = PortAbilityGetResponse{} }
func (m *PortAbilityGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortAbilityGetResponse) ProtoMessage()               {}
func (*PortAbilityGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

type PortAbilityLocalGetRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortAbilityLocalGetRequest) Reset()                    { *m = PortAbilityLocalGetRequest{} }
func (m *PortAbilityLocalGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortAbilityLocalGetRequest) ProtoMessage()               {}
func (*PortAbilityLocalGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

type PortAbilityLocalGetResponse struct {
	Ability *Ability `protobuf:"bytes,1,opt,name=ability" json:"ability,omitempty"`
}

func (m *PortAbilityLocalGetResponse) Reset()                    { *m = PortAbilityLocalGetResponse{} }
func (m *PortAbilityLocalGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortAbilityLocalGetResponse) ProtoMessage()               {}
func (*PortAbilityLocalGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *PortAbilityLocalGetResponse) GetAbility() *Ability {
	if m != nil {
		return m.Ability
	}
	return nil
}

type PortLinkscanSetRequest struct {
	Unit     int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port     int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Linkscan int64 `protobuf:"varint,3,opt,name=linkscan" json:"linkscan,omitempty"`
}

func (m *PortLinkscanSetRequest) Reset()                    { *m = PortLinkscanSetRequest{} }
func (m *PortLinkscanSetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortLinkscanSetRequest) ProtoMessage()               {}
func (*PortLinkscanSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

type PortLinkscanSetResponse struct {
}

func (m *PortLinkscanSetResponse) Reset()                    { *m = PortLinkscanSetResponse{} }
func (m *PortLinkscanSetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortLinkscanSetResponse) ProtoMessage()               {}
func (*PortLinkscanSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

type PortLinkscanGetRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortLinkscanGetRequest) Reset()                    { *m = PortLinkscanGetRequest{} }
func (m *PortLinkscanGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortLinkscanGetRequest) ProtoMessage()               {}
func (*PortLinkscanGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

type PortLinkscanGetResponse struct {
	Linkscan int64 `protobuf:"varint,1,opt,name=linkscan" json:"linkscan,omitempty"`
}

func (m *PortLinkscanGetResponse) Reset()                    { *m = PortLinkscanGetResponse{} }
func (m *PortLinkscanGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortLinkscanGetResponse) ProtoMessage()               {}
func (*PortLinkscanGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

type PortAutonegSetRequest struct {
	Unit   int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port   int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Enable bool  `protobuf:"varint,3,opt,name=enable" json:"enable,omitempty"`
}

func (m *PortAutonegSetRequest) Reset()                    { *m = PortAutonegSetRequest{} }
func (m *PortAutonegSetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortAutonegSetRequest) ProtoMessage()               {}
func (*PortAutonegSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

type PortAutonegSetResponse struct {
}

func (m *PortAutonegSetResponse) Reset()                    { *m = PortAutonegSetResponse{} }
func (m *PortAutonegSetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortAutonegSetResponse) ProtoMessage()               {}
func (*PortAutonegSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

type PortAutonegGetRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortAutonegGetRequest) Reset()                    { *m = PortAutonegGetRequest{} }
func (m *PortAutonegGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortAutonegGetRequest) ProtoMessage()               {}
func (*PortAutonegGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

type PortAutonegGetResponse struct {
	Enabled bool `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
}

func (m *PortAutonegGetResponse) Reset()                    { *m = PortAutonegGetResponse{} }
func (m *PortAutonegGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortAutonegGetResponse) ProtoMessage()               {}
func (*PortAutonegGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

type PortSpeedMAXRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortSpeedMAXRequest) Reset()                    { *m = PortSpeedMAXRequest{} }
func (m *PortSpeedMAXRequest) String() string            { return proto.CompactTextString(m) }
func (*PortSpeedMAXRequest) ProtoMessage()               {}
func (*PortSpeedMAXRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

type PortSpeedMAXResponse struct {
	Speed int64 `protobuf:"varint,1,opt,name=speed" json:"speed,omitempty"`
}

func (m *PortSpeedMAXResponse) Reset()                    { *m = PortSpeedMAXResponse{} }
func (m *PortSpeedMAXResponse) String() string            { return proto.CompactTextString(m) }
func (*PortSpeedMAXResponse) ProtoMessage()               {}
func (*PortSpeedMAXResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

type PortSpeedSetRequest struct {
	Unit  int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port  int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Speed int64 `protobuf:"varint,3,opt,name=speed" json:"speed,omitempty"`
}

func (m *PortSpeedSetRequest) Reset()                    { *m = PortSpeedSetRequest{} }
func (m *PortSpeedSetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortSpeedSetRequest) ProtoMessage()               {}
func (*PortSpeedSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

type PortSpeedSetResponse struct {
}

func (m *PortSpeedSetResponse) Reset()                    { *m = PortSpeedSetResponse{} }
func (m *PortSpeedSetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortSpeedSetResponse) ProtoMessage()               {}
func (*PortSpeedSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

type PortSpeedGetRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortSpeedGetRequest) Reset()                    { *m = PortSpeedGetRequest{} }
func (m *PortSpeedGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortSpeedGetRequest) ProtoMessage()               {}
func (*PortSpeedGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

type PortSpeedGetResponse struct {
	Speed int64 `protobuf:"varint,1,opt,name=speed" json:"speed,omitempty"`
}

func (m *PortSpeedGetResponse) Reset()                    { *m = PortSpeedGetResponse{} }
func (m *PortSpeedGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortSpeedGetResponse) ProtoMessage()               {}
func (*PortSpeedGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

type PortInterfaceSetRequest struct {
	Unit int64         `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64         `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Type InterfaceType `protobuf:"varint,3,opt,name=type,enum=port.InterfaceType" json:"type,omitempty"`
}

func (m *PortInterfaceSetRequest) Reset()                    { *m = PortInterfaceSetRequest{} }
func (m *PortInterfaceSetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortInterfaceSetRequest) ProtoMessage()               {}
func (*PortInterfaceSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

type PortInterfaceSetResponse struct {
}

func (m *PortInterfaceSetResponse) Reset()                    { *m = PortInterfaceSetResponse{} }
func (m *PortInterfaceSetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortInterfaceSetResponse) ProtoMessage()               {}
func (*PortInterfaceSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

type PortInterfaceGetRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortInterfaceGetRequest) Reset()                    { *m = PortInterfaceGetRequest{} }
func (m *PortInterfaceGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortInterfaceGetRequest) ProtoMessage()               {}
func (*PortInterfaceGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

type PortInterfaceGetResponse struct {
	Type InterfaceType `protobuf:"varint,1,opt,name=type,enum=port.InterfaceType" json:"type,omitempty"`
}

func (m *PortInterfaceGetResponse) Reset()                    { *m = PortInterfaceGetResponse{} }
func (m *PortInterfaceGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortInterfaceGetResponse) ProtoMessage()               {}
func (*PortInterfaceGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{52} }

type PortLinkStatusGetRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortLinkStatusGetRequest) Reset()                    { *m = PortLinkStatusGetRequest{} }
func (m *PortLinkStatusGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortLinkStatusGetRequest) ProtoMessage()               {}
func (*PortLinkStatusGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{53} }

type PortLinkStatusGetResponse struct {
	Up bool `protobuf:"varint,1,opt,name=up" json:"up,omitempty"`
}

func (m *PortLinkStatusGetResponse) Reset()                    { *m = PortLinkStatusGetResponse{} }
func (m *PortLinkStatusGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortLinkStatusGetResponse) ProtoMessage()               {}
func (*PortLinkStatusGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{54} }

type PortLinkFailedClearRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortLinkFailedClearRequest) Reset()                    { *m = PortLinkFailedClearRequest{} }
func (m *PortLinkFailedClearRequest) String() string            { return proto.CompactTextString(m) }
func (*PortLinkFailedClearRequest) ProtoMessage()               {}
func (*PortLinkFailedClearRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{55} }

type PortLinkFailedClearResponse struct {
}

func (m *PortLinkFailedClearResponse) Reset()                    { *m = PortLinkFailedClearResponse{} }
func (m *PortLinkFailedClearResponse) String() string            { return proto.CompactTextString(m) }
func (*PortLinkFailedClearResponse) ProtoMessage()               {}
func (*PortLinkFailedClearResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{56} }

type PortControlSetRequest struct {
	Unit  int64       `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port  int64       `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Type  ControlType `protobuf:"varint,3,opt,name=type,enum=port.ControlType" json:"type,omitempty"`
	Value int64       `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
}

func (m *PortControlSetRequest) Reset()                    { *m = PortControlSetRequest{} }
func (m *PortControlSetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortControlSetRequest) ProtoMessage()               {}
func (*PortControlSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{57} }

type PortControlSetResponse struct {
}

func (m *PortControlSetResponse) Reset()                    { *m = PortControlSetResponse{} }
func (m *PortControlSetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortControlSetResponse) ProtoMessage()               {}
func (*PortControlSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{58} }

type PortControlGetRequest struct {
	Unit int64       `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64       `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Type ControlType `protobuf:"varint,3,opt,name=type,enum=port.ControlType" json:"type,omitempty"`
}

func (m *PortControlGetRequest) Reset()                    { *m = PortControlGetRequest{} }
func (m *PortControlGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortControlGetRequest) ProtoMessage()               {}
func (*PortControlGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{59} }

type PortControlGetResponse struct {
	Value int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *PortControlGetResponse) Reset()                    { *m = PortControlGetResponse{} }
func (m *PortControlGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortControlGetResponse) ProtoMessage()               {}
func (*PortControlGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{60} }

type PortGportGetRequest struct {
	Unit int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Port int64 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PortGportGetRequest) Reset()                    { *m = PortGportGetRequest{} }
func (m *PortGportGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortGportGetRequest) ProtoMessage()               {}
func (*PortGportGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{61} }

type PortGportGetResponse struct {
	Gport int64 `protobuf:"varint,1,opt,name=gport" json:"gport,omitempty"`
}

func (m *PortGportGetResponse) Reset()                    { *m = PortGportGetResponse{} }
func (m *PortGportGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortGportGetResponse) ProtoMessage()               {}
func (*PortGportGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{62} }

type PortLocalGetRequest struct {
	Unit  int64 `protobuf:"varint,1,opt,name=unit" json:"unit,omitempty"`
	Gport int64 `protobuf:"varint,2,opt,name=gport" json:"gport,omitempty"`
}

func (m *PortLocalGetRequest) Reset()                    { *m = PortLocalGetRequest{} }
func (m *PortLocalGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PortLocalGetRequest) ProtoMessage()               {}
func (*PortLocalGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{63} }

type PortLocalGetResponse struct {
	Port int64 `protobuf:"varint,1,opt,name=port" json:"port,omitempty"`
}

func (m *PortLocalGetResponse) Reset()                    { *m = PortLocalGetResponse{} }
func (m *PortLocalGetResponse) String() string            { return proto.CompactTextString(m) }
func (*PortLocalGetResponse) ProtoMessage()               {}
func (*PortLocalGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{64} }

func init() {
	proto.RegisterType((*Ability)(nil), "port.Ability")
	proto.RegisterType((*PortConfig)(nil), "port.PortConfig")
	proto.RegisterType((*PortInfo)(nil), "port.PortInfo")
	proto.RegisterType((*InitRequest)(nil), "port.InitRequest")
	proto.RegisterType((*InitResponse)(nil), "port.InitResponse")
	proto.RegisterType((*ClearRequest)(nil), "port.ClearRequest")
	proto.RegisterType((*ClearResponse)(nil), "port.ClearResponse")
	proto.RegisterType((*ProbeRequest)(nil), "port.ProbeRequest")
	proto.RegisterType((*ProbeResponse)(nil), "port.ProbeResponse")
	proto.RegisterType((*DetachRequest)(nil), "port.DetachRequest")
	proto.RegisterType((*DetachResponse)(nil), "port.DetachResponse")
	proto.RegisterType((*GetConfigRequest)(nil), "port.GetConfigRequest")
	proto.RegisterType((*GetConfigResponse)(nil), "port.GetConfigResponse")
	proto.RegisterType((*GetPortNameRequest)(nil), "port.GetPortNameRequest")
	proto.RegisterType((*GetPortNameResponse)(nil), "port.GetPortNameResponse")
	proto.RegisterType((*PortEnableSetRequest)(nil), "port.PortEnableSetRequest")
	proto.RegisterType((*PortEnableSetResponse)(nil), "port.PortEnableSetResponse")
	proto.RegisterType((*PortEnableGetRequest)(nil), "port.PortEnableGetRequest")
	proto.RegisterType((*PortEnableGetResponse)(nil), "port.PortEnableGetResponse")
	proto.RegisterType((*PortAdvertSetRequest)(nil), "port.PortAdvertSetRequest")
	proto.RegisterType((*PortAdvertSetResponse)(nil), "port.PortAdvertSetResponse")
	proto.RegisterType((*PortAdvertGetRequest)(nil), "port.PortAdvertGetRequest")
	proto.RegisterType((*PortAdvertGetResponse)(nil), "port.PortAdvertGetResponse")
	proto.RegisterType((*PortAbilityAdvertSetRequest)(nil), "port.PortAbilityAdvertSetRequest")
	proto.RegisterType((*PortAbilityAdvertSetResponse)(nil), "port.PortAbilityAdvertSetResponse")
	proto.RegisterType((*PortAbilityAdvertGetRequest)(nil), "port.PortAbilityAdvertGetRequest")
	proto.RegisterType((*PortAbilityAdvertGetResponse)(nil), "port.PortAbilityAdvertGetResponse")
	proto.RegisterType((*PortAdvertRemoteGetRequest)(nil), "port.PortAdvertRemoteGetRequest")
	proto.RegisterType((*PortAdvertRemoteGetResponse)(nil), "port.PortAdvertRemoteGetResponse")
	proto.RegisterType((*PortAbilityRemoteGetRequest)(nil), "port.PortAbilityRemoteGetRequest")
	proto.RegisterType((*PortAbilityRemoteGetResponse)(nil), "port.PortAbilityRemoteGetResponse")
	proto.RegisterType((*PortAbilityGetRequest)(nil), "port.PortAbilityGetRequest")
	proto.RegisterType((*PortAbilityGetResponse)(nil), "port.PortAbilityGetResponse")
	proto.RegisterType((*PortAbilityLocalGetRequest)(nil), "port.PortAbilityLocalGetRequest")
	proto.RegisterType((*PortAbilityLocalGetResponse)(nil), "port.PortAbilityLocalGetResponse")
	proto.RegisterType((*PortLinkscanSetRequest)(nil), "port.PortLinkscanSetRequest")
	proto.RegisterType((*PortLinkscanSetResponse)(nil), "port.PortLinkscanSetResponse")
	proto.RegisterType((*PortLinkscanGetRequest)(nil), "port.PortLinkscanGetRequest")
	proto.RegisterType((*PortLinkscanGetResponse)(nil), "port.PortLinkscanGetResponse")
	proto.RegisterType((*PortAutonegSetRequest)(nil), "port.PortAutonegSetRequest")
	proto.RegisterType((*PortAutonegSetResponse)(nil), "port.PortAutonegSetResponse")
	proto.RegisterType((*PortAutonegGetRequest)(nil), "port.PortAutonegGetRequest")
	proto.RegisterType((*PortAutonegGetResponse)(nil), "port.PortAutonegGetResponse")
	proto.RegisterType((*PortSpeedMAXRequest)(nil), "port.PortSpeedMAXRequest")
	proto.RegisterType((*PortSpeedMAXResponse)(nil), "port.PortSpeedMAXResponse")
	proto.RegisterType((*PortSpeedSetRequest)(nil), "port.PortSpeedSetRequest")
	proto.RegisterType((*PortSpeedSetResponse)(nil), "port.PortSpeedSetResponse")
	proto.RegisterType((*PortSpeedGetRequest)(nil), "port.PortSpeedGetRequest")
	proto.RegisterType((*PortSpeedGetResponse)(nil), "port.PortSpeedGetResponse")
	proto.RegisterType((*PortInterfaceSetRequest)(nil), "port.PortInterfaceSetRequest")
	proto.RegisterType((*PortInterfaceSetResponse)(nil), "port.PortInterfaceSetResponse")
	proto.RegisterType((*PortInterfaceGetRequest)(nil), "port.PortInterfaceGetRequest")
	proto.RegisterType((*PortInterfaceGetResponse)(nil), "port.PortInterfaceGetResponse")
	proto.RegisterType((*PortLinkStatusGetRequest)(nil), "port.PortLinkStatusGetRequest")
	proto.RegisterType((*PortLinkStatusGetResponse)(nil), "port.PortLinkStatusGetResponse")
	proto.RegisterType((*PortLinkFailedClearRequest)(nil), "port.PortLinkFailedClearRequest")
	proto.RegisterType((*PortLinkFailedClearResponse)(nil), "port.PortLinkFailedClearResponse")
	proto.RegisterType((*PortControlSetRequest)(nil), "port.PortControlSetRequest")
	proto.RegisterType((*PortControlSetResponse)(nil), "port.PortControlSetResponse")
	proto.RegisterType((*PortControlGetRequest)(nil), "port.PortControlGetRequest")
	proto.RegisterType((*PortControlGetResponse)(nil), "port.PortControlGetResponse")
	proto.RegisterType((*PortGportGetRequest)(nil), "port.PortGportGetRequest")
	proto.RegisterType((*PortGportGetResponse)(nil), "port.PortGportGetResponse")
	proto.RegisterType((*PortLocalGetRequest)(nil), "port.PortLocalGetRequest")
	proto.RegisterType((*PortLocalGetResponse)(nil), "port.PortLocalGetResponse")
	proto.RegisterEnum("port.InterfaceType", InterfaceType_name, InterfaceType_value)
	proto.RegisterEnum("port.ControlType", ControlType_name, ControlType_value)
}

func init() { proto.RegisterFile("port.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1985 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x59, 0xeb, 0x72, 0xdb, 0xc6,
	0x15, 0x2e, 0x45, 0x59, 0x97, 0x95, 0x28, 0xad, 0x20, 0x45, 0x82, 0x64, 0x59, 0xb1, 0x11, 0x27,
	0x96, 0x65, 0xc7, 0x89, 0x19, 0xc5, 0xee, 0x25, 0x97, 0xd2, 0x10, 0xc8, 0x60, 0x04, 0x82, 0x28,
	0x00, 0x2a, 0x4c, 0x26, 0x33, 0x18, 0x88, 0x04, 0x69, 0xd6, 0x10, 0xc9, 0x92, 0xa0, 0x47, 0x9e,
	0xe9, 0x8b, 0xf4, 0x2d, 0xfa, 0xa3, 0x7f, 0x3a, 0x6d, 0x7f, 0xf5, 0x69, 0xfa, 0x16, 0x3d, 0x7b,
	0x01, 0xb9, 0x4b, 0xb2, 0x56, 0xc4, 0xb6, 0xbf, 0xb4, 0xe7, 0x3b, 0x67, 0xbf, 0x73, 0xdd, 0x5d,
	0x62, 0x84, 0x50, 0xaf, 0xdb, 0x4f, 0x9e, 0xf5, 0xfa, 0xdd, 0xa4, 0xab, 0x2c, 0x92, 0xb5, 0xf6,
	0xa7, 0x05, 0xb4, 0x5c, 0xb8, 0x6c, 0xc7, 0xed, 0xe4, 0x9d, 0x72, 0x82, 0xb6, 0x06, 0xbd, 0x28,
	0x6a, 0x04, 0xaf, 0xc3, 0xb8, 0x19, 0x34, 0x86, 0xbd, 0x38, 0xba, 0x56, 0x33, 0xf7, 0x33, 0xc7,
	0x8b, 0xee, 0x26, 0x55, 0x7c, 0x07, 0xf8, 0x19, 0x85, 0xc7, 0xb6, 0xcd, 0x61, 0x1c, 0xa7, 0xb6,
	0x0b, 0x82, 0x6d, 0x11, 0x70, 0x6e, 0xbb, 0x83, 0xee, 0xf4, 0xc2, 0xe1, 0x20, 0x52, 0xb3, 0x54,
	0xcf, 0x04, 0xe5, 0x10, 0xad, 0xb6, 0x3b, 0x49, 0xd4, 0x6f, 0x86, 0xf5, 0x48, 0x5d, 0xa4, 0x9a,
	0x31, 0xa0, 0xec, 0xa2, 0xa5, 0xab, 0xa8, 0xd1, 0x1e, 0x5e, 0xa9, 0x77, 0xa8, 0x8a, 0x4b, 0xca,
	0x01, 0x5a, 0x89, 0xbb, 0xdd, 0xde, 0x65, 0x58, 0x7f, 0xa3, 0x2e, 0x51, 0xcd, 0x48, 0x26, 0x7e,
	0x9a, 0x71, 0xd8, 0x1a, 0xa8, 0xcb, 0xcc, 0x0f, 0x15, 0x14, 0x8c, 0xb2, 0x51, 0x14, 0xa9, 0x2b,
	0x14, 0x23, 0x4b, 0x6a, 0x57, 0xbf, 0x0a, 0x7b, 0xea, 0x2a, 0xb7, 0x23, 0x02, 0xb1, 0x6b, 0x46,
	0x75, 0x75, 0x8d, 0xd9, 0xc1, 0x52, 0xfb, 0x6b, 0x16, 0x21, 0x07, 0x8a, 0xa4, 0x77, 0x3b, 0xcd,
	0x76, 0x4b, 0xd9, 0x40, 0x0b, 0xcd, 0x08, 0xea, 0x91, 0x3d, 0xce, 0xb9, 0xb0, 0x22, 0x72, 0x2b,
	0x82, 0x9c, 0xa9, 0xdc, 0xa2, 0xf2, 0x35, 0xc9, 0x91, 0xca, 0xd7, 0x54, 0xa6, 0x99, 0x51, 0x19,
	0x52, 0x5a, 0x47, 0x99, 0x08, 0xb2, 0x21, 0x62, 0x86, 0x6a, 0x5f, 0xb7, 0x20, 0x05, 0xaa, 0x7d,
	0xdd, 0x22, 0xee, 0x07, 0xf5, 0x36, 0x84, 0x4e, 0x00, 0xb2, 0xa4, 0x48, 0xb3, 0x0d, 0x81, 0x33,
	0xa4, 0xc9, 0x90, 0x5e, 0x1b, 0xc2, 0x66, 0x48, 0xaf, 0xad, 0x7c, 0x88, 0xd6, 0xe0, 0x4f, 0x30,
	0x18, 0x5e, 0x92, 0x6e, 0xaa, 0x88, 0x6a, 0x10, 0x40, 0x1e, 0x43, 0x14, 0x05, 0xd1, 0x3e, 0x43,
	0x5a, 0x44, 0x43, 0xd7, 0x84, 0xa6, 0xde, 0x1b, 0xaa, 0xeb, 0x8c, 0x06, 0x96, 0x04, 0x09, 0xe3,
	0x58, 0xcd, 0x31, 0x04, 0x96, 0xca, 0x5d, 0xb4, 0x3a, 0x48, 0xa0, 0xa8, 0x01, 0xb4, 0x44, 0xdd,
	0xa0, 0xf8, 0x0a, 0x05, 0xcc, 0x4e, 0x32, 0x56, 0x46, 0xd7, 0x89, 0xba, 0x29, 0x28, 0x8d, 0x6b,
	0xca, 0x9e, 0x34, 0xae, 0x54, 0xcc, 0xb8, 0x60, 0x49, 0x90, 0x5e, 0xb7, 0xa3, 0x6e, 0x31, 0x04,
	0x96, 0x24, 0xaa, 0x38, 0x6e, 0x37, 0x54, 0x85, 0x45, 0x45, 0xd6, 0xb4, 0x7c, 0xb1, 0xba, 0xcd,
	0xcb, 0x17, 0x93, 0x5d, 0xfd, 0xfa, 0x3b, 0x75, 0x87, 0xed, 0x82, 0x25, 0x41, 0x3a, 0xed, 0xa6,
	0xba, 0xcb, 0x10, 0x58, 0x2a, 0x2a, 0x5a, 0xae, 0x77, 0x3b, 0x49, 0xbf, 0x1b, 0xab, 0x7b, 0x14,
	0x4d, 0x45, 0xed, 0x5f, 0x0b, 0x68, 0x85, 0xf4, 0xce, 0xec, 0x34, 0xbb, 0xa4, 0x4a, 0x61, 0x3d,
	0x69, 0x77, 0x3b, 0xc1, 0x55, 0x38, 0x78, 0x43, 0x47, 0x1a, 0xaa, 0xc4, 0xa0, 0x32, 0x20, 0xca,
	0x03, 0xb4, 0x2e, 0x18, 0xe4, 0xe9, 0x20, 0xe7, 0xdc, 0xb5, 0xb1, 0x45, 0x9e, 0x0c, 0x64, 0xd4,
	0x09, 0x2f, 0x63, 0x36, 0xc5, 0x59, 0x97, 0x4b, 0x84, 0x3b, 0x6e, 0x77, 0xde, 0x04, 0x90, 0x7f,
	0x32, 0x1c, 0xd0, 0x41, 0xce, 0xba, 0x88, 0x40, 0x1e, 0x45, 0x94, 0x7d, 0xb4, 0x12, 0x0e, 0x93,
	0x6e, 0xd0, 0x89, 0x5a, 0x74, 0x96, 0xb3, 0xee, 0x32, 0x91, 0xed, 0xa8, 0x45, 0x06, 0x91, 0x9e,
	0x15, 0x3a, 0xc9, 0x59, 0x97, 0x09, 0xc4, 0x13, 0x3f, 0x4f, 0xcb, 0xcc, 0x13, 0x93, 0xe8, 0xe8,
	0x03, 0xed, 0xa0, 0x1e, 0x76, 0xe8, 0x34, 0x67, 0xdd, 0x91, 0x4c, 0x98, 0xe2, 0x28, 0xec, 0x77,
	0xe8, 0x48, 0xe7, 0x5c, 0x26, 0x90, 0xf2, 0x34, 0xda, 0xa0, 0xef, 0x37, 0x60, 0x32, 0xa8, 0x67,
	0x2e, 0x2a, 0x47, 0x08, 0xbd, 0x8d, 0x43, 0x18, 0xeb, 0x18, 0x0e, 0x1c, 0x9d, 0x79, 0x28, 0xc8,
	0x18, 0x51, 0x9e, 0xa0, 0xad, 0x61, 0x27, 0x09, 0x5b, 0x2d, 0x38, 0xe1, 0xbd, 0x7e, 0xbb, 0xdb,
	0x87, 0xfb, 0x01, 0x06, 0x86, 0x70, 0xe0, 0x54, 0xe1, 0x70, 0x5c, 0x7b, 0x80, 0xd6, 0xcc, 0x4e,
	0x3b, 0x71, 0xa3, 0x3f, 0x0c, 0xa3, 0x01, 0x1d, 0xb9, 0x21, 0x88, 0xb4, 0xcc, 0x59, 0x97, 0xae,
	0xb5, 0x0d, 0xb4, 0xce, 0x4c, 0x06, 0xd0, 0xfe, 0x41, 0xa4, 0x69, 0x68, 0x5d, 0x27, 0x31, 0xbe,
	0x6f, 0xcf, 0x26, 0xca, 0x71, 0x1b, 0xbe, 0xe9, 0x05, 0x5a, 0x77, 0xfa, 0xdd, 0xcb, 0xe8, 0x3d,
	0x9b, 0xe8, 0xbc, 0x5f, 0x5e, 0xf5, 0xf8, 0xb1, 0xa4, 0x6b, 0xed, 0x23, 0x94, 0xe3, 0xfb, 0x18,
	0xd1, 0xc8, 0x28, 0x23, 0x18, 0xbd, 0x44, 0xb9, 0xb3, 0x08, 0x66, 0xf8, 0xf5, 0x6d, 0xd9, 0x1f,
	0xa2, 0x8d, 0x74, 0xe3, 0x7b, 0xe8, 0x3f, 0x41, 0xb8, 0x14, 0xf1, 0x9b, 0xe4, 0x7d, 0x49, 0x7f,
	0x8d, 0xb6, 0x04, 0x3b, 0x4e, 0x78, 0x8c, 0x96, 0xea, 0x14, 0xa1, 0xa6, 0x6b, 0x79, 0xfc, 0x8c,
	0xde, 0xe3, 0xe3, 0xbb, 0xc9, 0xe5, 0x7a, 0xed, 0x2b, 0xa4, 0xc0, 0x76, 0xa2, 0xb0, 0xc3, 0xab,
	0x1b, 0x0b, 0x45, 0x2e, 0x86, 0x05, 0x86, 0xd1, 0xc7, 0xe0, 0x31, 0xda, 0x96, 0x76, 0x8f, 0xf3,
	0xe9, 0x80, 0x4c, 0xb7, 0xaf, 0xba, 0x74, 0xad, 0x5d, 0xa0, 0x1d, 0x62, 0x67, 0xd0, 0x43, 0xe0,
	0x45, 0xc9, 0x2d, 0x5d, 0x4d, 0x1c, 0xa7, 0x95, 0xf4, 0x38, 0x69, 0x7b, 0xe8, 0x83, 0x09, 0x5e,
	0xde, 0xfc, 0x6f, 0x44, 0x87, 0xa5, 0x5b, 0x3b, 0xd4, 0x3e, 0x13, 0x89, 0x4b, 0x63, 0x62, 0x21,
	0x92, 0x8c, 0x14, 0x49, 0x8d, 0x39, 0x2c, 0x34, 0xde, 0x46, 0xfd, 0x64, 0x8e, 0x0c, 0xe1, 0xf0,
	0x85, 0xec, 0x61, 0xe5, 0xef, 0x5e, 0x2a, 0xa6, 0x39, 0x0a, 0xcc, 0x72, 0x8e, 0x4c, 0x31, 0x47,
	0x8e, 0xcf, 0x45, 0x62, 0x31, 0x47, 0x21, 0x96, 0x8c, 0x1c, 0x4b, 0x07, 0xdd, 0xa5, 0x5b, 0x98,
	0x38, 0x77, 0xb2, 0x8f, 0xe4, 0x64, 0xd7, 0xf2, 0x39, 0x36, 0xa2, 0x9c, 0x77, 0xec, 0xef, 0x08,
	0x1d, 0xce, 0xf6, 0xc7, 0x4b, 0x60, 0xcc, 0x88, 0x67, 0x8e, 0x4a, 0x94, 0x66, 0xb8, 0x11, 0x0b,
	0xf2, 0x48, 0x2e, 0xc8, 0x7f, 0x8e, 0xf7, 0x0c, 0x1d, 0x8c, 0x4b, 0xea, 0x46, 0x57, 0xdd, 0x64,
	0x9e, 0xe1, 0x7b, 0xc9, 0xb3, 0x9a, 0x64, 0x99, 0x6e, 0xcf, 0xc4, 0xa8, 0xc8, 0xe5, 0x98, 0xdb,
	0xbf, 0x5c, 0x8e, 0xe9, 0x00, 0x7e, 0x76, 0x39, 0xbe, 0xe5, 0x13, 0xc6, 0xc4, 0x39, 0x22, 0xc9,
	0xa3, 0xdd, 0x49, 0x82, 0x1b, 0x67, 0x34, 0xed, 0x01, 0x13, 0xad, 0x6e, 0x3d, 0x8c, 0xe7, 0xf0,
	0x5c, 0x94, 0x4a, 0x39, 0x66, 0xb9, 0x6d, 0x09, 0x7e, 0x62, 0x19, 0x58, 0xfc, 0xe9, 0x9d, 0xe3,
	0xb0, 0x88, 0x0f, 0x79, 0x56, 0x7e, 0xc8, 0xb5, 0x7d, 0xb4, 0x37, 0xc5, 0xce, 0x8f, 0xc6, 0x6f,
	0x65, 0xc7, 0x73, 0x94, 0xe0, 0x4b, 0x99, 0x5c, 0x4c, 0x5f, 0x8c, 0x29, 0x33, 0x11, 0xd3, 0xf7,
	0xbc, 0xe9, 0xf0, 0xab, 0x05, 0x7e, 0xc4, 0xfc, 0x0f, 0x2f, 0x7b, 0x95, 0x0f, 0x83, 0x40, 0xcc,
	0x73, 0xfd, 0x56, 0x72, 0xf9, 0x5f, 0xcc, 0x99, 0x40, 0x30, 0x9e, 0x33, 0xe6, 0xbe, 0xc1, 0x2f,
	0xfc, 0x54, 0x84, 0xb7, 0x77, 0x9b, 0xec, 0xf1, 0xc8, 0xaf, 0xb0, 0x72, 0xa1, 0x76, 0x5b, 0x97,
	0x4f, 0xd9, 0xed, 0x3d, 0xde, 0xce, 0x1d, 0x8e, 0x7e, 0xe5, 0x65, 0x84, 0x5f, 0x79, 0x9a, 0x27,
	0x38, 0x9b, 0xa3, 0xa4, 0x23, 0xd2, 0xac, 0x48, 0xba, 0x2b, 0x84, 0x20, 0x96, 0x53, 0xcc, 0x6c,
	0x8e, 0x62, 0x8a, 0x99, 0x89, 0xa5, 0x9c, 0x9d, 0xd9, 0xef, 0xd9, 0x94, 0x99, 0xe9, 0xb7, 0xdc,
	0x5c, 0xcf, 0xc9, 0x62, 0xf2, 0xae, 0xc7, 0xc6, 0x65, 0x23, 0xbf, 0xcd, 0x4e, 0xe2, 0x88, 0xd0,
	0x07, 0x95, 0x4b, 0x0d, 0xb4, 0x03, 0xa4, 0x4e, 0xfb, 0xe2, 0x49, 0x17, 0x26, 0xe2, 0x98, 0x23,
	0x71, 0x7d, 0x82, 0x5e, 0xbe, 0x30, 0x58, 0x8c, 0x99, 0x9b, 0x62, 0x7c, 0xc5, 0x48, 0xac, 0xd1,
	0x27, 0xc1, 0x1c, 0x81, 0x3c, 0x41, 0xfb, 0x33, 0x38, 0x78, 0x24, 0xf0, 0xe5, 0x34, 0xec, 0xf1,
	0x61, 0x86, 0x55, 0x7a, 0x5f, 0x12, 0xe3, 0x62, 0xd8, 0x86, 0xc9, 0xbe, 0xe9, 0xa7, 0xf6, 0x4c,
	0x97, 0xf7, 0xd8, 0x7d, 0x39, 0xc5, 0xc2, 0xab, 0xfb, 0x47, 0x76, 0x42, 0x75, 0xf6, 0xbd, 0x35,
	0x47, 0x8f, 0x3f, 0x96, 0x7a, 0xbc, 0xc5, 0xea, 0xc7, 0xe9, 0xc6, 0xd5, 0x23, 0x33, 0xf6, 0x36,
	0x8c, 0x87, 0x11, 0xff, 0xb2, 0x62, 0x42, 0x7a, 0x73, 0x88, 0xde, 0x79, 0x5c, 0x4d, 0x29, 0xae,
	0xd2, 0xff, 0x2b, 0x2e, 0xed, 0x99, 0x14, 0xc1, 0xc4, 0xa9, 0x60, 0x11, 0x67, 0xc4, 0x88, 0xf9,
	0x11, 0x2c, 0x11, 0xba, 0xf9, 0x8f, 0xe0, 0x78, 0xfb, 0xd8, 0x59, 0x8b, 0x1a, 0x73, 0x67, 0x54,
	0x80, 0xeb, 0x93, 0x3a, 0xfb, 0x39, 0x4f, 0xe5, 0x88, 0x60, 0x41, 0x24, 0x38, 0x61, 0xee, 0xa6,
	0x5e, 0xc9, 0x34, 0xb4, 0xcc, 0x38, 0xb4, 0x93, 0xbf, 0xac, 0xa0, 0x9c, 0x34, 0xf7, 0xca, 0x16,
	0x00, 0xc5, 0xc0, 0xff, 0xc1, 0x31, 0x02, 0xbb, 0xa2, 0xd7, 0x6c, 0xfc, 0x0b, 0xf8, 0x76, 0x5f,
	0x1f, 0x41, 0x55, 0xcb, 0xc2, 0x19, 0x65, 0x13, 0xbe, 0x1a, 0x39, 0x52, 0x36, 0x4d, 0xbc, 0x20,
	0x9a, 0x94, 0x08, 0x92, 0x15, 0x79, 0x3c, 0x0a, 0x2d, 0x8a, 0xbb, 0xfc, 0x57, 0x26, 0xbe, 0x23,
	0xda, 0xd4, 0xa8, 0xcd, 0x92, 0x08, 0xb9, 0x14, 0x5a, 0x96, 0xa0, 0xb7, 0x04, 0x5a, 0x11, 0x99,
	0xbc, 0xa2, 0x89, 0x57, 0x45, 0xa0, 0x06, 0x00, 0x82, 0x73, 0x85, 0x52, 0xe0, 0xdc, 0xc5, 0x6b,
	0xa2, 0xc1, 0xb9, 0x7b, 0x8a, 0xd7, 0x45, 0x03, 0xdd, 0xc5, 0x39, 0xd1, 0x40, 0x07, 0x83, 0x0d,
	0x29, 0x38, 0xab, 0x50, 0x35, 0xf1, 0xa6, 0xb8, 0xc7, 0x73, 0x31, 0x96, 0x22, 0xab, 0x11, 0x93,
	0x2d, 0xb1, 0x10, 0x14, 0x51, 0xa4, 0x42, 0x38, 0x04, 0xda, 0x86, 0x4e, 0x6c, 0xa4, 0xd0, 0xef,
	0x58, 0x71, 0x76, 0xc4, 0x8d, 0xa6, 0x75, 0x6e, 0xe3, 0x0f, 0xc4, 0x88, 0x5c, 0xfd, 0x07, 0xbc,
	0x0b, 0xed, 0xc6, 0x29, 0x50, 0x2c, 0xf8, 0x81, 0x63, 0x3a, 0x06, 0xde, 0x13, 0xf9, 0x75, 0xca,
	0xa5, 0x8a, 0x5c, 0x3a, 0xf1, 0xb8, 0x2f, 0x46, 0x6e, 0xb9, 0xf8, 0x40, 0xe4, 0xb6, 0x20, 0xdb,
	0xbb, 0x52, 0x45, 0x01, 0x38, 0x94, 0x0a, 0x58, 0xc3, 0xf7, 0x44, 0xf9, 0x47, 0x17, 0x1f, 0x89,
	0x3e, 0x3c, 0xf7, 0xf9, 0xe7, 0xf8, 0x43, 0x91, 0xa2, 0xe2, 0x5b, 0xf8, 0xbe, 0x54, 0x52, 0xa7,
	0x8a, 0x1f, 0x48, 0x16, 0x96, 0x83, 0x35, 0x91, 0xa4, 0x52, 0x28, 0x3b, 0xf8, 0x23, 0xd1, 0xc4,
	0x70, 0x1d, 0xfc, 0x50, 0xb9, 0x8b, 0xf6, 0x46, 0x43, 0x53, 0x0e, 0x4c, 0xdb, 0x37, 0x5c, 0xbb,
	0x60, 0x05, 0xce, 0xb9, 0x8f, 0x3f, 0x96, 0xa3, 0xce, 0xe3, 0x4f, 0xe4, 0x36, 0xe7, 0xf1, 0x23,
	0xb9, 0xad, 0x79, 0x7c, 0x2c, 0x35, 0xa8, 0x68, 0xe6, 0xf1, 0x63, 0xb1, 0x1b, 0xb4, 0xd1, 0x79,
	0x7c, 0x22, 0x55, 0x90, 0x64, 0xf7, 0x44, 0x44, 0xce, 0x09, 0xf2, 0x54, 0x44, 0x2c, 0x82, 0x7c,
	0x2a, 0xd6, 0xc8, 0x70, 0xf1, 0x33, 0x39, 0x99, 0x3c, 0xfe, 0x4c, 0x06, 0x4e, 0xf1, 0xe7, 0xd2,
	0x14, 0xd6, 0xf0, 0x73, 0x29, 0xdc, 0x5a, 0x1e, 0xe7, 0x65, 0xe0, 0x14, 0x7f, 0x21, 0x0e, 0x01,
	0xe9, 0x6d, 0xa0, 0xe7, 0x75, 0x7c, 0x3a, 0x03, 0x2d, 0xe3, 0x2f, 0xc5, 0xcd, 0x17, 0x30, 0xb0,
	0x2f, 0xe4, 0xb6, 0xe7, 0xf1, 0x4b, 0x19, 0x28, 0xe3, 0x5f, 0xca, 0x53, 0xef, 0x38, 0x26, 0xfe,
	0x95, 0x34, 0x60, 0x95, 0xaa, 0xed, 0xe3, 0x5f, 0x9f, 0xfc, 0x73, 0x11, 0xad, 0x09, 0xd7, 0x2a,
	0xfc, 0x2e, 0xdb, 0xd1, 0x2b, 0xb6, 0xef, 0x56, 0x2c, 0x66, 0x57, 0xb5, 0xcf, 0xed, 0xca, 0xf7,
	0xe4, 0xee, 0x80, 0xc0, 0x24, 0x8d, 0xe9, 0x9c, 0xc2, 0xf9, 0x9d, 0x46, 0x5f, 0xc0, 0x21, 0x7e,
	0x88, 0xee, 0x4b, 0xa8, 0xef, 0x56, 0x3d, 0x1f, 0x5a, 0xae, 0x57, 0xca, 0xa6, 0x5d, 0x0a, 0x2e,
	0xac, 0x82, 0x0d, 0xa7, 0x40, 0x43, 0x47, 0x92, 0xd5, 0x59, 0x05, 0x2e, 0x2a, 0x3f, 0xd0, 0xbf,
	0x33, 0xf4, 0x73, 0x66, 0xb3, 0xa7, 0x3c, 0x45, 0xc7, 0x92, 0x8d, 0x51, 0x72, 0x0d, 0x83, 0x2a,
	0x03, 0xc7, 0x35, 0x83, 0xaa, 0x67, 0x78, 0x64, 0x82, 0x88, 0x00, 0xad, 0x3d, 0x42, 0x07, 0x92,
	0x75, 0x2a, 0x80, 0xb9, 0xe1, 0x41, 0x91, 0x0e, 0x91, 0x2a, 0xe9, 0x9d, 0xa2, 0x1e, 0xb8, 0x86,
	0x6e, 0x98, 0x17, 0x06, 0xfe, 0x8d, 0x72, 0x0f, 0xed, 0x4f, 0x69, 0x7d, 0xb7, 0x60, 0x7b, 0x65,
	0xd3, 0xc7, 0x5f, 0xcd, 0xdc, 0xac, 0x5b, 0x05, 0x0f, 0x42, 0xc0, 0x5f, 0x2b, 0xf7, 0xd1, 0xe1,
	0x94, 0xd6, 0x01, 0x65, 0x50, 0x74, 0x0b, 0x65, 0xb0, 0xf8, 0x66, 0xaa, 0xb4, 0x56, 0x3e, 0x28,
	0x57, 0xc0, 0x71, 0x71, 0x2a, 0x6c, 0xcf, 0x87, 0x4b, 0x01, 0x54, 0xae, 0x67, 0xfe, 0x68, 0xe0,
	0x9f, 0x40, 0x2f, 0x07, 0x76, 0x51, 0x23, 0xf9, 0x1b, 0x76, 0xe1, 0x95, 0x65, 0xe0, 0xbf, 0x65,
	0x94, 0xc7, 0xe8, 0xe1, 0x0c, 0xbd, 0x5f, 0xb5, 0x6d, 0xc3, 0x0a, 0x5e, 0x15, 0x3c, 0xe3, 0x2c,
	0xb8, 0xb0, 0xcd, 0x33, 0xfc, 0xf7, 0x8c, 0xf2, 0xe9, 0x44, 0x3d, 0x99, 0xe9, 0x99, 0x51, 0x2c,
	0x54, 0x2d, 0x3f, 0xdd, 0xc2, 0x99, 0xff, 0x91, 0x81, 0x67, 0x58, 0x6e, 0xa4, 0x07, 0x67, 0xdb,
	0x82, 0x2e, 0xdb, 0xd0, 0x06, 0xc8, 0xed, 0xcc, 0xf0, 0x7c, 0xfc, 0xe7, 0x85, 0xcb, 0x25, 0xfa,
	0xcf, 0x8c, 0x2f, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xda, 0x21, 0x45, 0xda, 0x18, 0x00,
	0x00,
}
