// Code generated by protoc-gen-go.
// source: driver.proto
// DO NOT EDIT!

/*
Package driver is a generated protocol buffer package.

It is generated from these files:
	driver.proto

It has these top-level messages:
	Config
	InitRequest
	InitResponse
	GetVersionRequest
	GetVersionResponse
*/
package driver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	ConfigFileName   string `protobuf:"bytes,1,opt,name=config_file_name,json=configFileName" json:"config_file_name,omitempty"`
	Flags            int64  `protobuf:"varint,2,opt,name=flags" json:"flags,omitempty"`
	WarmBootFileName string `protobuf:"bytes,3,opt,name=warm_boot_file_name,json=warmBootFileName" json:"warm_boot_file_name,omitempty"`
	RmConfigFileName string `protobuf:"bytes,4,opt,name=rm_config_file_name,json=rmConfigFileName" json:"rm_config_file_name,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InitRequest struct {
	Config *Config `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
}

func (m *InitRequest) Reset()                    { *m = InitRequest{} }
func (m *InitRequest) String() string            { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()               {}
func (*InitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InitRequest) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type InitResponse struct {
}

func (m *InitResponse) Reset()                    { *m = InitResponse{} }
func (m *InitResponse) String() string            { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()               {}
func (*InitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetVersionRequest struct {
}

func (m *GetVersionRequest) Reset()                    { *m = GetVersionRequest{} }
func (m *GetVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetVersionRequest) ProtoMessage()               {}
func (*GetVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetVersionResponse struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *GetVersionResponse) Reset()                    { *m = GetVersionResponse{} }
func (m *GetVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetVersionResponse) ProtoMessage()               {}
func (*GetVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*Config)(nil), "driver.Config")
	proto.RegisterType((*InitRequest)(nil), "driver.InitRequest")
	proto.RegisterType((*InitResponse)(nil), "driver.InitResponse")
	proto.RegisterType((*GetVersionRequest)(nil), "driver.GetVersionRequest")
	proto.RegisterType((*GetVersionResponse)(nil), "driver.GetVersionResponse")
}

func init() { proto.RegisterFile("driver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x50, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x56, 0x28, 0x18, 0x71, 0xad, 0xa2, 0xe2, 0x32, 0x64, 0x44, 0x1e, 0x50, 0x17, 0x32, 0x80,
	0x78, 0x01, 0x22, 0x81, 0x58, 0x18, 0x3c, 0xb0, 0x46, 0x09, 0x5c, 0x22, 0x4b, 0x89, 0x1d, 0x6c,
	0x13, 0xde, 0x88, 0xe7, 0xc4, 0xf8, 0x0c, 0x0a, 0xea, 0xe6, 0xef, 0xf7, 0x7c, 0x07, 0x9b, 0x37,
	0xab, 0x66, 0xb4, 0xe5, 0x64, 0x8d, 0x37, 0x9c, 0x11, 0x12, 0x5f, 0x19, 0xb0, 0xca, 0xe8, 0x4e,
	0xf5, 0x7c, 0x0f, 0xdb, 0xd7, 0xf8, 0xaa, 0x3b, 0x35, 0x60, 0xad, 0x9b, 0x11, 0x8b, 0xec, 0x32,
	0xdb, 0x9f, 0xc9, 0x9c, 0xf8, 0x87, 0x40, 0x3f, 0x07, 0x96, 0x5f, 0xc0, 0x49, 0x37, 0x34, 0xbd,
	0x2b, 0x8e, 0x82, 0xbc, 0x92, 0x04, 0xf8, 0x35, 0xec, 0x3e, 0x1b, 0x3b, 0xd6, 0xad, 0x31, 0x7e,
	0x51, 0xb1, 0x8a, 0x15, 0xdb, 0x1f, 0xe9, 0x3e, 0x28, 0x7f, 0x25, 0xc1, 0x1e, 0xcc, 0x07, 0x13,
	0x8f, 0xc9, 0x6e, 0xc7, 0xea, 0xdf, 0x4c, 0x71, 0x07, 0xeb, 0x27, 0xad, 0xbc, 0xc4, 0xf7, 0x0f,
	0x74, 0x9e, 0x5f, 0x01, 0xa3, 0x68, 0xfc, 0xe2, 0xfa, 0x26, 0x2f, 0xd3, 0x7a, 0x14, 0x93, 0x49,
	0x15, 0x39, 0x6c, 0x28, 0xe6, 0x26, 0xa3, 0x1d, 0x8a, 0x1d, 0x9c, 0x3f, 0xa2, 0x7f, 0x41, 0xeb,
	0x94, 0xd1, 0xa9, 0x4c, 0x94, 0xc0, 0x97, 0x24, 0x59, 0x79, 0x01, 0xa7, 0x33, 0x51, 0xe9, 0x0c,
	0xbf, 0xb0, 0x65, 0xf1, 0x86, 0xb7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x64, 0xfc, 0xff, 0x19,
	0x53, 0x01, 0x00, 0x00,
}
